"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
from swarmeval.proto.swarmeval.control.v1 import control_pb2 as _control_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class ControlServiceStub:
    """ControlService is the orchestrator control plane's API. Until edge exists (M4) it is bound to
    the internal network and has no authentication. Behavior: docs/services/orchestrator.md.
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> ControlServiceAsyncStub: ...
    SubmitRuns: _grpc.UnaryUnaryMultiCallable[_control_pb2.SubmitRunsRequest, _control_pb2.SubmitRunsResponse]
    """Queues one run per variant and epoch of a case: a bundle, pushed to the case library as
    PushCase pushes it, or a revision already there. A case that does not load is
    INVALID_ARGUMENT, with the loader's message; an unknown case or revision is NOT_FOUND; an
    archived case is FAILED_PRECONDITION.
    """
    SubmitSuite: _grpc.UnaryUnaryMultiCallable[_control_pb2.SubmitSuiteRequest, _control_pb2.SubmitSuiteResponse]
    """Loads a suite with the case bundles it names and queues every case's runs in one
    transaction, each case its own submission under one suite label: a suite with a case that
    does not load queues nothing. The format: docs/case-format.md#suites. INVALID_ARGUMENT names
    the suite entry at fault.
    """
    GetRun: _grpc.UnaryUnaryMultiCallable[_control_pb2.GetRunRequest, _control_pb2.GetRunResponse]
    ListRuns: _grpc.UnaryUnaryMultiCallable[_control_pb2.ListRunsRequest, _control_pb2.ListRunsResponse]
    """Newest first."""
    CancelRun: _grpc.UnaryUnaryMultiCallable[_control_pb2.CancelRunRequest, _control_pb2.CancelRunResponse]
    """A queued run never starts; a running one stops at its owner's next step, keeps its events,
    and is not scored. Cancelling a finished run is FAILED_PRECONDITION.
    """
    ResumeRun: _grpc.UnaryUnaryMultiCallable[_control_pb2.ResumeRunRequest, _control_pb2.ResumeRunResponse]
    """A run paused for a person (a Monitor's `pause`) goes on from where it stopped. A run that is
    not paused is FAILED_PRECONDITION.
    """
    ForkRun: _grpc.UnaryUnaryMultiCallable[_control_pb2.ForkRunRequest, _control_pb2.ForkRunResponse]
    """A new run that goes on from a finished run's state at the start of the turn `at_event_id`
    happened in, with `edits` applied: the same case
    revision, variant, and seed, its sandboxes restored from the stored file contents. Not an
    epoch: reports keep forks apart. An unknown run or event is NOT_FOUND; a run still going, an
    event before the first turn, or an edit that does not fit the state there is
    FAILED_PRECONDITION.
    """
    StreamEvents: _grpc.UnaryStreamMultiCallable[_control_pb2.StreamEventsRequest, _control_pb2.StreamEventsResponse]
    """A run's events with seq greater than `after_seq`, live while the run is going. The stream
    ends once the run has finished and every event was sent.
    """
    ListModels: _grpc.UnaryUnaryMultiCallable[_control_pb2.ListModelsRequest, _control_pb2.ListModelsResponse]
    """The model names runs may use: what model-gateway serves. UNAVAILABLE when model-gateway
    cannot be reached.
    """
    PushCase: _grpc.UnaryUnaryMultiCallable[_control_pb2.PushCaseRequest, _control_pb2.PushCaseResponse]
    """The case library (docs/services/orchestrator.md#case-library). A case is `workspace` and
    `case_id`, as its `case.yaml` names them; its revisions are numbered from 1 and never change.

    Validates a case bundle and stores it as the newest revision of the case its `case.yaml`
    names, creating the case on its first push. A bundle with the same bytes as the newest
    revision makes no new one. A case that does not load is INVALID_ARGUMENT and nothing is
    stored; an archived case is FAILED_PRECONDITION.
    """
    UpdateCaseFiles: _grpc.UnaryUnaryMultiCallable[_control_pb2.UpdateCaseFilesRequest, _control_pb2.UpdateCaseFilesResponse]
    """Applies file changes to revision `base_revision` and stores the result as the next
    revision, validated as PushCase validates. ABORTED when `base_revision` is not the newest
    revision; the message names the newest. `base_revision` 0 creates the case from the written
    files alone.
    """
    GetCase: _grpc.UnaryUnaryMultiCallable[_control_pb2.GetCaseRequest, _control_pb2.GetCaseResponse]
    ListCases: _grpc.UnaryUnaryMultiCallable[_control_pb2.ListCasesRequest, _control_pb2.ListCasesResponse]
    """By workspace, then case id."""
    ListCaseRevisions: _grpc.UnaryUnaryMultiCallable[_control_pb2.ListCaseRevisionsRequest, _control_pb2.ListCaseRevisionsResponse]
    """Newest first."""
    GetCaseRevision: _grpc.UnaryUnaryMultiCallable[_control_pb2.GetCaseRevisionRequest, _control_pb2.GetCaseRevisionResponse]
    """One revision with its files."""
    ArchiveCase: _grpc.UnaryUnaryMultiCallable[_control_pb2.ArchiveCaseRequest, _control_pb2.ArchiveCaseResponse]
    """An archived case is left out of ListCases by default and takes no pushes, edits, or runs.
    Its revisions and bundles stay: runs reference them.
    """
    UnarchiveCase: _grpc.UnaryUnaryMultiCallable[_control_pb2.UnarchiveCaseRequest, _control_pb2.UnarchiveCaseResponse]

@_typing.type_check_only
class ControlServiceAsyncStub(ControlServiceStub):
    """ControlService is the orchestrator control plane's API. Until edge exists (M4) it is bound to
    the internal network and has no authentication. Behavior: docs/services/orchestrator.md.
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    SubmitRuns: _aio.UnaryUnaryMultiCallable[_control_pb2.SubmitRunsRequest, _control_pb2.SubmitRunsResponse]  # type: ignore[assignment]
    """Queues one run per variant and epoch of a case: a bundle, pushed to the case library as
    PushCase pushes it, or a revision already there. A case that does not load is
    INVALID_ARGUMENT, with the loader's message; an unknown case or revision is NOT_FOUND; an
    archived case is FAILED_PRECONDITION.
    """
    SubmitSuite: _aio.UnaryUnaryMultiCallable[_control_pb2.SubmitSuiteRequest, _control_pb2.SubmitSuiteResponse]  # type: ignore[assignment]
    """Loads a suite with the case bundles it names and queues every case's runs in one
    transaction, each case its own submission under one suite label: a suite with a case that
    does not load queues nothing. The format: docs/case-format.md#suites. INVALID_ARGUMENT names
    the suite entry at fault.
    """
    GetRun: _aio.UnaryUnaryMultiCallable[_control_pb2.GetRunRequest, _control_pb2.GetRunResponse]  # type: ignore[assignment]
    ListRuns: _aio.UnaryUnaryMultiCallable[_control_pb2.ListRunsRequest, _control_pb2.ListRunsResponse]  # type: ignore[assignment]
    """Newest first."""
    CancelRun: _aio.UnaryUnaryMultiCallable[_control_pb2.CancelRunRequest, _control_pb2.CancelRunResponse]  # type: ignore[assignment]
    """A queued run never starts; a running one stops at its owner's next step, keeps its events,
    and is not scored. Cancelling a finished run is FAILED_PRECONDITION.
    """
    ResumeRun: _aio.UnaryUnaryMultiCallable[_control_pb2.ResumeRunRequest, _control_pb2.ResumeRunResponse]  # type: ignore[assignment]
    """A run paused for a person (a Monitor's `pause`) goes on from where it stopped. A run that is
    not paused is FAILED_PRECONDITION.
    """
    ForkRun: _aio.UnaryUnaryMultiCallable[_control_pb2.ForkRunRequest, _control_pb2.ForkRunResponse]  # type: ignore[assignment]
    """A new run that goes on from a finished run's state at the start of the turn `at_event_id`
    happened in, with `edits` applied: the same case
    revision, variant, and seed, its sandboxes restored from the stored file contents. Not an
    epoch: reports keep forks apart. An unknown run or event is NOT_FOUND; a run still going, an
    event before the first turn, or an edit that does not fit the state there is
    FAILED_PRECONDITION.
    """
    StreamEvents: _aio.UnaryStreamMultiCallable[_control_pb2.StreamEventsRequest, _control_pb2.StreamEventsResponse]  # type: ignore[assignment]
    """A run's events with seq greater than `after_seq`, live while the run is going. The stream
    ends once the run has finished and every event was sent.
    """
    ListModels: _aio.UnaryUnaryMultiCallable[_control_pb2.ListModelsRequest, _control_pb2.ListModelsResponse]  # type: ignore[assignment]
    """The model names runs may use: what model-gateway serves. UNAVAILABLE when model-gateway
    cannot be reached.
    """
    PushCase: _aio.UnaryUnaryMultiCallable[_control_pb2.PushCaseRequest, _control_pb2.PushCaseResponse]  # type: ignore[assignment]
    """The case library (docs/services/orchestrator.md#case-library). A case is `workspace` and
    `case_id`, as its `case.yaml` names them; its revisions are numbered from 1 and never change.

    Validates a case bundle and stores it as the newest revision of the case its `case.yaml`
    names, creating the case on its first push. A bundle with the same bytes as the newest
    revision makes no new one. A case that does not load is INVALID_ARGUMENT and nothing is
    stored; an archived case is FAILED_PRECONDITION.
    """
    UpdateCaseFiles: _aio.UnaryUnaryMultiCallable[_control_pb2.UpdateCaseFilesRequest, _control_pb2.UpdateCaseFilesResponse]  # type: ignore[assignment]
    """Applies file changes to revision `base_revision` and stores the result as the next
    revision, validated as PushCase validates. ABORTED when `base_revision` is not the newest
    revision; the message names the newest. `base_revision` 0 creates the case from the written
    files alone.
    """
    GetCase: _aio.UnaryUnaryMultiCallable[_control_pb2.GetCaseRequest, _control_pb2.GetCaseResponse]  # type: ignore[assignment]
    ListCases: _aio.UnaryUnaryMultiCallable[_control_pb2.ListCasesRequest, _control_pb2.ListCasesResponse]  # type: ignore[assignment]
    """By workspace, then case id."""
    ListCaseRevisions: _aio.UnaryUnaryMultiCallable[_control_pb2.ListCaseRevisionsRequest, _control_pb2.ListCaseRevisionsResponse]  # type: ignore[assignment]
    """Newest first."""
    GetCaseRevision: _aio.UnaryUnaryMultiCallable[_control_pb2.GetCaseRevisionRequest, _control_pb2.GetCaseRevisionResponse]  # type: ignore[assignment]
    """One revision with its files."""
    ArchiveCase: _aio.UnaryUnaryMultiCallable[_control_pb2.ArchiveCaseRequest, _control_pb2.ArchiveCaseResponse]  # type: ignore[assignment]
    """An archived case is left out of ListCases by default and takes no pushes, edits, or runs.
    Its revisions and bundles stay: runs reference them.
    """
    UnarchiveCase: _aio.UnaryUnaryMultiCallable[_control_pb2.UnarchiveCaseRequest, _control_pb2.UnarchiveCaseResponse]  # type: ignore[assignment]

class ControlServiceServicer(metaclass=_abc_1.ABCMeta):
    """ControlService is the orchestrator control plane's API. Until edge exists (M4) it is bound to
    the internal network and has no authentication. Behavior: docs/services/orchestrator.md.
    """

    @_abc_1.abstractmethod
    def SubmitRuns(
        self,
        request: _control_pb2.SubmitRunsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_control_pb2.SubmitRunsResponse, _abc.Awaitable[_control_pb2.SubmitRunsResponse]]:
        """Queues one run per variant and epoch of a case: a bundle, pushed to the case library as
        PushCase pushes it, or a revision already there. A case that does not load is
        INVALID_ARGUMENT, with the loader's message; an unknown case or revision is NOT_FOUND; an
        archived case is FAILED_PRECONDITION.
        """

    @_abc_1.abstractmethod
    def SubmitSuite(
        self,
        request: _control_pb2.SubmitSuiteRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_control_pb2.SubmitSuiteResponse, _abc.Awaitable[_control_pb2.SubmitSuiteResponse]]:
        """Loads a suite with the case bundles it names and queues every case's runs in one
        transaction, each case its own submission under one suite label: a suite with a case that
        does not load queues nothing. The format: docs/case-format.md#suites. INVALID_ARGUMENT names
        the suite entry at fault.
        """

    @_abc_1.abstractmethod
    def GetRun(
        self,
        request: _control_pb2.GetRunRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_control_pb2.GetRunResponse, _abc.Awaitable[_control_pb2.GetRunResponse]]: ...

    @_abc_1.abstractmethod
    def ListRuns(
        self,
        request: _control_pb2.ListRunsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_control_pb2.ListRunsResponse, _abc.Awaitable[_control_pb2.ListRunsResponse]]:
        """Newest first."""

    @_abc_1.abstractmethod
    def CancelRun(
        self,
        request: _control_pb2.CancelRunRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_control_pb2.CancelRunResponse, _abc.Awaitable[_control_pb2.CancelRunResponse]]:
        """A queued run never starts; a running one stops at its owner's next step, keeps its events,
        and is not scored. Cancelling a finished run is FAILED_PRECONDITION.
        """

    @_abc_1.abstractmethod
    def ResumeRun(
        self,
        request: _control_pb2.ResumeRunRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_control_pb2.ResumeRunResponse, _abc.Awaitable[_control_pb2.ResumeRunResponse]]:
        """A run paused for a person (a Monitor's `pause`) goes on from where it stopped. A run that is
        not paused is FAILED_PRECONDITION.
        """

    @_abc_1.abstractmethod
    def ForkRun(
        self,
        request: _control_pb2.ForkRunRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_control_pb2.ForkRunResponse, _abc.Awaitable[_control_pb2.ForkRunResponse]]:
        """A new run that goes on from a finished run's state at the start of the turn `at_event_id`
        happened in, with `edits` applied: the same case
        revision, variant, and seed, its sandboxes restored from the stored file contents. Not an
        epoch: reports keep forks apart. An unknown run or event is NOT_FOUND; a run still going, an
        event before the first turn, or an edit that does not fit the state there is
        FAILED_PRECONDITION.
        """

    @_abc_1.abstractmethod
    def StreamEvents(
        self,
        request: _control_pb2.StreamEventsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_control_pb2.StreamEventsResponse], _abc.AsyncIterator[_control_pb2.StreamEventsResponse]]:
        """A run's events with seq greater than `after_seq`, live while the run is going. The stream
        ends once the run has finished and every event was sent.
        """

    @_abc_1.abstractmethod
    def ListModels(
        self,
        request: _control_pb2.ListModelsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_control_pb2.ListModelsResponse, _abc.Awaitable[_control_pb2.ListModelsResponse]]:
        """The model names runs may use: what model-gateway serves. UNAVAILABLE when model-gateway
        cannot be reached.
        """

    @_abc_1.abstractmethod
    def PushCase(
        self,
        request: _control_pb2.PushCaseRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_control_pb2.PushCaseResponse, _abc.Awaitable[_control_pb2.PushCaseResponse]]:
        """The case library (docs/services/orchestrator.md#case-library). A case is `workspace` and
        `case_id`, as its `case.yaml` names them; its revisions are numbered from 1 and never change.

        Validates a case bundle and stores it as the newest revision of the case its `case.yaml`
        names, creating the case on its first push. A bundle with the same bytes as the newest
        revision makes no new one. A case that does not load is INVALID_ARGUMENT and nothing is
        stored; an archived case is FAILED_PRECONDITION.
        """

    @_abc_1.abstractmethod
    def UpdateCaseFiles(
        self,
        request: _control_pb2.UpdateCaseFilesRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_control_pb2.UpdateCaseFilesResponse, _abc.Awaitable[_control_pb2.UpdateCaseFilesResponse]]:
        """Applies file changes to revision `base_revision` and stores the result as the next
        revision, validated as PushCase validates. ABORTED when `base_revision` is not the newest
        revision; the message names the newest. `base_revision` 0 creates the case from the written
        files alone.
        """

    @_abc_1.abstractmethod
    def GetCase(
        self,
        request: _control_pb2.GetCaseRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_control_pb2.GetCaseResponse, _abc.Awaitable[_control_pb2.GetCaseResponse]]: ...

    @_abc_1.abstractmethod
    def ListCases(
        self,
        request: _control_pb2.ListCasesRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_control_pb2.ListCasesResponse, _abc.Awaitable[_control_pb2.ListCasesResponse]]:
        """By workspace, then case id."""

    @_abc_1.abstractmethod
    def ListCaseRevisions(
        self,
        request: _control_pb2.ListCaseRevisionsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_control_pb2.ListCaseRevisionsResponse, _abc.Awaitable[_control_pb2.ListCaseRevisionsResponse]]:
        """Newest first."""

    @_abc_1.abstractmethod
    def GetCaseRevision(
        self,
        request: _control_pb2.GetCaseRevisionRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_control_pb2.GetCaseRevisionResponse, _abc.Awaitable[_control_pb2.GetCaseRevisionResponse]]:
        """One revision with its files."""

    @_abc_1.abstractmethod
    def ArchiveCase(
        self,
        request: _control_pb2.ArchiveCaseRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_control_pb2.ArchiveCaseResponse, _abc.Awaitable[_control_pb2.ArchiveCaseResponse]]:
        """An archived case is left out of ListCases by default and takes no pushes, edits, or runs.
        Its revisions and bundles stay: runs reference them.
        """

    @_abc_1.abstractmethod
    def UnarchiveCase(
        self,
        request: _control_pb2.UnarchiveCaseRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_control_pb2.UnarchiveCaseResponse, _abc.Awaitable[_control_pb2.UnarchiveCaseResponse]]: ...

def add_ControlServiceServicer_to_server(servicer: ControlServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
