"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import struct_pb2 as _struct_pb2
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class SubmitRunsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CASE_BUNDLE_FIELD_NUMBER: _builtins.int
    CASE_FIELD_NUMBER: _builtins.int
    OVERRIDES_FIELD_NUMBER: _builtins.int
    EPOCHS_FIELD_NUMBER: _builtins.int
    SUITE_FIELD_NUMBER: _builtins.int
    ACTOR_FIELD_NUMBER: _builtins.int
    case_bundle: _builtins.bytes
    """The case directory as an uncompressed tar archive, with `case.yaml` at its root. Set this
    or `case`, not both.
    """
    epochs: _builtins.int
    """Runs per variant. Zero means the case's `epochs`."""
    suite: _builtins.str
    """Labels the submissions of one suite run, so a report can cover them together: lowercase
    letters, digits, `_`, `.`, and `-`, starting with a letter or digit. Empty for none.
    """
    actor: _builtins.str
    """Who asks, as edge authenticated them; empty for internal tooling. Recorded on the runs."""
    @_builtins.property
    def case(self) -> Global___CaseRevisionRef:
        """A revision in the case library, instead of a bundle."""

    @_builtins.property
    def overrides(self) -> _struct_pb2.Struct:
        """Variant axis → list of values, replacing that axis's values in the case."""

    def __init__(
        self,
        *,
        case_bundle: _builtins.bytes = ...,
        case: Global___CaseRevisionRef | None = ...,
        overrides: _struct_pb2.Struct | None = ...,
        epochs: _builtins.int = ...,
        suite: _builtins.str = ...,
        actor: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["case", b"case", "overrides", b"overrides"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["actor", b"actor", "case", b"case", "case_bundle", b"case_bundle", "epochs", b"epochs", "overrides", b"overrides", "suite", b"suite"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SubmitRunsRequest: _TypeAlias = SubmitRunsRequest  # noqa: Y015

@_typing.final
class CaseRevisionRef(_message.Message):
    """One revision of a case in the library."""

    DESCRIPTOR: _descriptor.Descriptor

    WORKSPACE_FIELD_NUMBER: _builtins.int
    CASE_ID_FIELD_NUMBER: _builtins.int
    REVISION_FIELD_NUMBER: _builtins.int
    workspace: _builtins.str
    case_id: _builtins.str
    revision: _builtins.int
    """Zero means the newest."""
    def __init__(
        self,
        *,
        workspace: _builtins.str = ...,
        case_id: _builtins.str = ...,
        revision: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["case_id", b"case_id", "revision", b"revision", "workspace", b"workspace"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CaseRevisionRef: _TypeAlias = CaseRevisionRef  # noqa: Y015

@_typing.final
class SubmitRunsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUBMISSION_ID_FIELD_NUMBER: _builtins.int
    RUN_IDS_FIELD_NUMBER: _builtins.int
    CASE_REVISION_FIELD_NUMBER: _builtins.int
    submission_id: _builtins.str
    case_revision: _builtins.int
    """The revision the runs use."""
    @_builtins.property
    def run_ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        submission_id: _builtins.str = ...,
        run_ids: _abc.Iterable[_builtins.str] | None = ...,
        case_revision: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["case_revision", b"case_revision", "run_ids", b"run_ids", "submission_id", b"submission_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SubmitRunsResponse: _TypeAlias = SubmitRunsResponse  # noqa: Y015

@_typing.final
class SubmitSuiteRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class CaseBundlesEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.bytes
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.bytes = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    SUITE_YAML_FIELD_NUMBER: _builtins.int
    CASE_BUNDLES_FIELD_NUMBER: _builtins.int
    ACTOR_FIELD_NUMBER: _builtins.int
    suite_yaml: _builtins.str
    """The suite file as written."""
    actor: _builtins.str
    @_builtins.property
    def case_bundles(self) -> _containers.ScalarMap[_builtins.str, _builtins.bytes]:
        """Each `cases[].path` of the suite, as written there, → that case directory as a tar
        archive. A path the suite names more than once is sent once. The whole request is at most
        64 MiB.
        """

    def __init__(
        self,
        *,
        suite_yaml: _builtins.str = ...,
        case_bundles: _abc.Mapping[_builtins.str, _builtins.bytes] | None = ...,
        actor: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["actor", b"actor", "case_bundles", b"case_bundles", "suite_yaml", b"suite_yaml"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SubmitSuiteRequest: _TypeAlias = SubmitSuiteRequest  # noqa: Y015

@_typing.final
class SuiteSubmission(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CASE_ID_FIELD_NUMBER: _builtins.int
    SUBMISSION_ID_FIELD_NUMBER: _builtins.int
    RUN_IDS_FIELD_NUMBER: _builtins.int
    CASE_REVISION_FIELD_NUMBER: _builtins.int
    case_id: _builtins.str
    submission_id: _builtins.str
    case_revision: _builtins.int
    @_builtins.property
    def run_ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        case_id: _builtins.str = ...,
        submission_id: _builtins.str = ...,
        run_ids: _abc.Iterable[_builtins.str] | None = ...,
        case_revision: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["case_id", b"case_id", "case_revision", b"case_revision", "run_ids", b"run_ids", "submission_id", b"submission_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SuiteSubmission: _TypeAlias = SuiteSubmission  # noqa: Y015

@_typing.final
class SubmitSuiteResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUITE_FIELD_NUMBER: _builtins.int
    SUBMISSIONS_FIELD_NUMBER: _builtins.int
    suite: _builtins.str
    """`<suite id>.<8 hex>`, for reports over the whole suite."""
    @_builtins.property
    def submissions(self) -> _containers.RepeatedCompositeFieldContainer[Global___SuiteSubmission]:
        """One per suite entry, in the suite's order."""

    def __init__(
        self,
        *,
        suite: _builtins.str = ...,
        submissions: _abc.Iterable[Global___SuiteSubmission] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["submissions", b"submissions", "suite", b"suite"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SubmitSuiteResponse: _TypeAlias = SubmitSuiteResponse  # noqa: Y015

@_typing.final
class Run(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    SUBMISSION_ID_FIELD_NUMBER: _builtins.int
    CASE_ID_FIELD_NUMBER: _builtins.int
    WORKSPACE_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    VARIANT_FIELD_NUMBER: _builtins.int
    TASK_ARGS_FIELD_NUMBER: _builtins.int
    EPOCH_FIELD_NUMBER: _builtins.int
    EPOCHS_FIELD_NUMBER: _builtins.int
    CASE_SHA256_FIELD_NUMBER: _builtins.int
    OWNER_ID_FIELD_NUMBER: _builtins.int
    ISOLATION_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    CREATED_AT_FIELD_NUMBER: _builtins.int
    STARTED_AT_FIELD_NUMBER: _builtins.int
    FINISHED_AT_FIELD_NUMBER: _builtins.int
    REPLACES_FIELD_NUMBER: _builtins.int
    SUITE_FIELD_NUMBER: _builtins.int
    FORKED_FROM_FIELD_NUMBER: _builtins.int
    FORK_SEQ_FIELD_NUMBER: _builtins.int
    FIDELITY_FIELD_NUMBER: _builtins.int
    SUBMITTED_BY_FIELD_NUMBER: _builtins.int
    CANCELLED_BY_FIELD_NUMBER: _builtins.int
    RESUMED_BY_FIELD_NUMBER: _builtins.int
    CASE_REVISION_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    submission_id: _builtins.str
    case_id: _builtins.str
    workspace: _builtins.str
    status: _builtins.str
    """`queued`, `running`, `paused`, `interrupted`, `done`, `failed`, or `cancelled`."""
    variant: _builtins.int
    epoch: _builtins.int
    epochs: _builtins.int
    case_sha256: _builtins.str
    owner_id: _builtins.str
    isolation: _builtins.str
    """Container runtime the run's sandboxes got: `runc` or `runsc`. Empty until they exist."""
    error: _builtins.str
    """Why the run failed or was interrupted."""
    replaces: _builtins.str
    """The interrupted run this one reruns at a new epoch; empty for a run the submission asked for."""
    suite: _builtins.str
    """The suite label of the run's submission; empty for none."""
    forked_from: _builtins.str
    """For a fork: the run it goes on from, and the last of that run's events it starts after."""
    fork_seq: _builtins.int
    fidelity: _builtins.str
    """For a fork, once its sandboxes are restored: `fs_restored` when every recorded file change
    up to the fork point was restored, `fs_partial` when some could not be.
    """
    submitted_by: _builtins.str
    """The actor of the submission or fork that queued the run; a rerun keeps its predecessor's.
    Empty when the request named none.
    """
    cancelled_by: _builtins.str
    """The actor of the CancelRun that cancelled the run, and of the last ResumeRun."""
    resumed_by: _builtins.str
    case_revision: _builtins.int
    """The case library revision the run uses; `case_sha256` is that revision's bundle."""
    @_builtins.property
    def task_args(self) -> _struct_pb2.Struct:
        """The variant's axis values."""

    @_builtins.property
    def created_at(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def started_at(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def finished_at(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
        submission_id: _builtins.str = ...,
        case_id: _builtins.str = ...,
        workspace: _builtins.str = ...,
        status: _builtins.str = ...,
        variant: _builtins.int = ...,
        task_args: _struct_pb2.Struct | None = ...,
        epoch: _builtins.int = ...,
        epochs: _builtins.int = ...,
        case_sha256: _builtins.str = ...,
        owner_id: _builtins.str = ...,
        isolation: _builtins.str = ...,
        error: _builtins.str = ...,
        created_at: _timestamp_pb2.Timestamp | None = ...,
        started_at: _timestamp_pb2.Timestamp | None = ...,
        finished_at: _timestamp_pb2.Timestamp | None = ...,
        replaces: _builtins.str = ...,
        suite: _builtins.str = ...,
        forked_from: _builtins.str = ...,
        fork_seq: _builtins.int = ...,
        fidelity: _builtins.str = ...,
        submitted_by: _builtins.str = ...,
        cancelled_by: _builtins.str = ...,
        resumed_by: _builtins.str = ...,
        case_revision: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["created_at", b"created_at", "finished_at", b"finished_at", "started_at", b"started_at", "task_args", b"task_args"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["cancelled_by", b"cancelled_by", "case_id", b"case_id", "case_revision", b"case_revision", "case_sha256", b"case_sha256", "created_at", b"created_at", "epoch", b"epoch", "epochs", b"epochs", "error", b"error", "fidelity", b"fidelity", "finished_at", b"finished_at", "fork_seq", b"fork_seq", "forked_from", b"forked_from", "isolation", b"isolation", "owner_id", b"owner_id", "replaces", b"replaces", "resumed_by", b"resumed_by", "run_id", b"run_id", "started_at", b"started_at", "status", b"status", "submission_id", b"submission_id", "submitted_by", b"submitted_by", "suite", b"suite", "task_args", b"task_args", "variant", b"variant", "workspace", b"workspace"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Run: _TypeAlias = Run  # noqa: Y015

@_typing.final
class GetRunRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["run_id", b"run_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetRunRequest: _TypeAlias = GetRunRequest  # noqa: Y015

@_typing.final
class GetRunResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def run(self) -> Global___Run: ...
    def __init__(
        self,
        *,
        run: Global___Run | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["run", b"run"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["run", b"run"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetRunResponse: _TypeAlias = GetRunResponse  # noqa: Y015

@_typing.final
class ListRunsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUBMISSION_ID_FIELD_NUMBER: _builtins.int
    CASE_ID_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    SUITE_FIELD_NUMBER: _builtins.int
    LIMIT_FIELD_NUMBER: _builtins.int
    submission_id: _builtins.str
    """Filters; empty matches everything."""
    case_id: _builtins.str
    status: _builtins.str
    suite: _builtins.str
    limit: _builtins.int
    """Zero means 100."""
    def __init__(
        self,
        *,
        submission_id: _builtins.str = ...,
        case_id: _builtins.str = ...,
        status: _builtins.str = ...,
        suite: _builtins.str = ...,
        limit: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["case_id", b"case_id", "limit", b"limit", "status", b"status", "submission_id", b"submission_id", "suite", b"suite"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListRunsRequest: _TypeAlias = ListRunsRequest  # noqa: Y015

@_typing.final
class ListRunsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUNS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def runs(self) -> _containers.RepeatedCompositeFieldContainer[Global___Run]: ...
    def __init__(
        self,
        *,
        runs: _abc.Iterable[Global___Run] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["runs", b"runs"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListRunsResponse: _TypeAlias = ListRunsResponse  # noqa: Y015

@_typing.final
class CancelRunRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    ACTOR_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    actor: _builtins.str
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
        actor: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["actor", b"actor", "run_id", b"run_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CancelRunRequest: _TypeAlias = CancelRunRequest  # noqa: Y015

@_typing.final
class CancelRunResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def run(self) -> Global___Run: ...
    def __init__(
        self,
        *,
        run: Global___Run | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["run", b"run"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["run", b"run"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CancelRunResponse: _TypeAlias = CancelRunResponse  # noqa: Y015

@_typing.final
class ResumeRunRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    ACTOR_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    actor: _builtins.str
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
        actor: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["actor", b"actor", "run_id", b"run_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ResumeRunRequest: _TypeAlias = ResumeRunRequest  # noqa: Y015

@_typing.final
class ResumeRunResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def run(self) -> Global___Run: ...
    def __init__(
        self,
        *,
        run: Global___Run | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["run", b"run"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["run", b"run"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ResumeRunResponse: _TypeAlias = ResumeRunResponse  # noqa: Y015

@_typing.final
class ForkRunRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    AT_EVENT_ID_FIELD_NUMBER: _builtins.int
    EDITS_FIELD_NUMBER: _builtins.int
    ACTOR_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    at_event_id: _builtins.str
    actor: _builtins.str
    @_builtins.property
    def edits(self) -> _containers.RepeatedCompositeFieldContainer[Global___ForkEdit]: ...
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
        at_event_id: _builtins.str = ...,
        edits: _abc.Iterable[Global___ForkEdit] | None = ...,
        actor: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["actor", b"actor", "at_event_id", b"at_event_id", "edits", b"edits", "run_id", b"run_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ForkRunRequest: _TypeAlias = ForkRunRequest  # noqa: Y015

@_typing.final
class ForkEdit(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REPLACE_MESSAGE_FIELD_NUMBER: _builtins.int
    DELETE_MESSAGE_FIELD_NUMBER: _builtins.int
    REPLACE_DELIVERY_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def replace_message(self) -> Global___ReplaceMessage: ...
    @_builtins.property
    def delete_message(self) -> Global___DeleteMessage: ...
    @_builtins.property
    def replace_delivery(self) -> Global___ReplaceDelivery: ...
    def __init__(
        self,
        *,
        replace_message: Global___ReplaceMessage | None = ...,
        delete_message: Global___DeleteMessage | None = ...,
        replace_delivery: Global___ReplaceDelivery | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["delete_message", b"delete_message", "edit", b"edit", "replace_delivery", b"replace_delivery", "replace_message", b"replace_message"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["delete_message", b"delete_message", "edit", b"edit", "replace_delivery", b"replace_delivery", "replace_message", b"replace_message"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_edit: _TypeAlias = _typing.Literal["replace_message", "delete_message", "replace_delivery"]  # noqa: Y015
    _WhichOneofArgType_edit: _TypeAlias = _typing.Literal["edit", b"edit"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_edit) -> _WhichOneofReturnType_edit | None: ...

Global___ForkEdit: _TypeAlias = ForkEdit  # noqa: Y015

@_typing.final
class ReplaceMessage(_message.Message):
    """The text of message `index` in an agent's context at the fork point."""

    DESCRIPTOR: _descriptor.Descriptor

    AGENT_ID_FIELD_NUMBER: _builtins.int
    INDEX_FIELD_NUMBER: _builtins.int
    CONTENT_FIELD_NUMBER: _builtins.int
    agent_id: _builtins.str
    index: _builtins.int
    content: _builtins.str
    def __init__(
        self,
        *,
        agent_id: _builtins.str = ...,
        index: _builtins.int = ...,
        content: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["agent_id", b"agent_id", "content", b"content", "index", b"index"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReplaceMessage: _TypeAlias = ReplaceMessage  # noqa: Y015

@_typing.final
class DeleteMessage(_message.Message):
    """A user message (a delivery or an injection) in an agent's context at the fork point."""

    DESCRIPTOR: _descriptor.Descriptor

    AGENT_ID_FIELD_NUMBER: _builtins.int
    INDEX_FIELD_NUMBER: _builtins.int
    agent_id: _builtins.str
    index: _builtins.int
    def __init__(
        self,
        *,
        agent_id: _builtins.str = ...,
        index: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["agent_id", b"agent_id", "index", b"index"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeleteMessage: _TypeAlias = DeleteMessage  # noqa: Y015

@_typing.final
class ReplaceDelivery(_message.Message):
    """Other content for a message routed to `recipient` but not yet delivered at the fork point."""

    DESCRIPTOR: _descriptor.Descriptor

    SEND_EVENT_ID_FIELD_NUMBER: _builtins.int
    RECIPIENT_FIELD_NUMBER: _builtins.int
    CONTENT_FIELD_NUMBER: _builtins.int
    send_event_id: _builtins.str
    recipient: _builtins.str
    content: _builtins.str
    def __init__(
        self,
        *,
        send_event_id: _builtins.str = ...,
        recipient: _builtins.str = ...,
        content: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["content", b"content", "recipient", b"recipient", "send_event_id", b"send_event_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReplaceDelivery: _TypeAlias = ReplaceDelivery  # noqa: Y015

@_typing.final
class ForkRunResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def run(self) -> Global___Run: ...
    def __init__(
        self,
        *,
        run: Global___Run | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["run", b"run"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["run", b"run"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ForkRunResponse: _TypeAlias = ForkRunResponse  # noqa: Y015

@_typing.final
class StreamEventsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    AFTER_SEQ_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    after_seq: _builtins.int
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
        after_seq: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["after_seq", b"after_seq", "run_id", b"run_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StreamEventsRequest: _TypeAlias = StreamEventsRequest  # noqa: Y015

@_typing.final
class StreamEventsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SEQ_FIELD_NUMBER: _builtins.int
    EVENT_ID_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    AGENT_ID_FIELD_NUMBER: _builtins.int
    PAYLOAD_JSON_FIELD_NUMBER: _builtins.int
    LINE_FIELD_NUMBER: _builtins.int
    seq: _builtins.int
    event_id: _builtins.str
    type: _builtins.str
    """The Inspect event type, or an InfoEvent's `swarmeval.<kind>` source."""
    agent_id: _builtins.str
    payload_json: _builtins.str
    """The stored Inspect event, as JSON."""
    line: _builtins.str
    """The event on one line, as the judge and the timeline show it (swarmeval.events.render),
    cut at 2,000 characters.
    """
    def __init__(
        self,
        *,
        seq: _builtins.int = ...,
        event_id: _builtins.str = ...,
        type: _builtins.str = ...,
        agent_id: _builtins.str = ...,
        payload_json: _builtins.str = ...,
        line: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["agent_id", b"agent_id", "event_id", b"event_id", "line", b"line", "payload_json", b"payload_json", "seq", b"seq", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StreamEventsResponse: _TypeAlias = StreamEventsResponse  # noqa: Y015

@_typing.final
class Case(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    WORKSPACE_FIELD_NUMBER: _builtins.int
    CASE_ID_FIELD_NUMBER: _builtins.int
    CREATED_AT_FIELD_NUMBER: _builtins.int
    ARCHIVED_AT_FIELD_NUMBER: _builtins.int
    LATEST_FIELD_NUMBER: _builtins.int
    workspace: _builtins.str
    case_id: _builtins.str
    @_builtins.property
    def created_at(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def archived_at(self) -> _timestamp_pb2.Timestamp:
        """Unset while the case is not archived."""

    @_builtins.property
    def latest(self) -> Global___CaseRevision:
        """The newest revision."""

    def __init__(
        self,
        *,
        workspace: _builtins.str = ...,
        case_id: _builtins.str = ...,
        created_at: _timestamp_pb2.Timestamp | None = ...,
        archived_at: _timestamp_pb2.Timestamp | None = ...,
        latest: Global___CaseRevision | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["archived_at", b"archived_at", "created_at", b"created_at", "latest", b"latest"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["archived_at", b"archived_at", "case_id", b"case_id", "created_at", b"created_at", "latest", b"latest", "workspace", b"workspace"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Case: _TypeAlias = Case  # noqa: Y015

@_typing.final
class CaseRevision(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    WORKSPACE_FIELD_NUMBER: _builtins.int
    CASE_ID_FIELD_NUMBER: _builtins.int
    REVISION_FIELD_NUMBER: _builtins.int
    BUNDLE_SHA256_FIELD_NUMBER: _builtins.int
    ACTOR_FIELD_NUMBER: _builtins.int
    NOTE_FIELD_NUMBER: _builtins.int
    CREATED_AT_FIELD_NUMBER: _builtins.int
    workspace: _builtins.str
    case_id: _builtins.str
    revision: _builtins.int
    bundle_sha256: _builtins.str
    actor: _builtins.str
    """The actor of the request that made the revision; empty when it named none."""
    note: _builtins.str
    @_builtins.property
    def created_at(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        workspace: _builtins.str = ...,
        case_id: _builtins.str = ...,
        revision: _builtins.int = ...,
        bundle_sha256: _builtins.str = ...,
        actor: _builtins.str = ...,
        note: _builtins.str = ...,
        created_at: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["created_at", b"created_at"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["actor", b"actor", "bundle_sha256", b"bundle_sha256", "case_id", b"case_id", "created_at", b"created_at", "note", b"note", "revision", b"revision", "workspace", b"workspace"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CaseRevision: _TypeAlias = CaseRevision  # noqa: Y015

@_typing.final
class CaseFile(_message.Message):
    """A regular file or a symbolic link of a case bundle."""

    DESCRIPTOR: _descriptor.Descriptor

    PATH_FIELD_NUMBER: _builtins.int
    CONTENT_FIELD_NUMBER: _builtins.int
    MODE_FIELD_NUMBER: _builtins.int
    LINK_TARGET_FIELD_NUMBER: _builtins.int
    path: _builtins.str
    """Relative to the case directory, with `/` separators."""
    content: _builtins.bytes
    mode: _builtins.int
    """Unix permission bits."""
    link_target: _builtins.str
    """For a symbolic link, where it points; `content` is empty."""
    def __init__(
        self,
        *,
        path: _builtins.str = ...,
        content: _builtins.bytes = ...,
        mode: _builtins.int = ...,
        link_target: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["content", b"content", "link_target", b"link_target", "mode", b"mode", "path", b"path"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CaseFile: _TypeAlias = CaseFile  # noqa: Y015

@_typing.final
class PushCaseRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CASE_BUNDLE_FIELD_NUMBER: _builtins.int
    ACTOR_FIELD_NUMBER: _builtins.int
    NOTE_FIELD_NUMBER: _builtins.int
    case_bundle: _builtins.bytes
    actor: _builtins.str
    note: _builtins.str
    """What changed, for the revision list. At most 1,000 characters."""
    def __init__(
        self,
        *,
        case_bundle: _builtins.bytes = ...,
        actor: _builtins.str = ...,
        note: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["actor", b"actor", "case_bundle", b"case_bundle", "note", b"note"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PushCaseRequest: _TypeAlias = PushCaseRequest  # noqa: Y015

@_typing.final
class PushCaseResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REVISION_FIELD_NUMBER: _builtins.int
    CREATED_FIELD_NUMBER: _builtins.int
    created: _builtins.bool
    """False when the bundle was the newest revision already."""
    @_builtins.property
    def revision(self) -> Global___CaseRevision: ...
    def __init__(
        self,
        *,
        revision: Global___CaseRevision | None = ...,
        created: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["revision", b"revision"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["created", b"created", "revision", b"revision"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PushCaseResponse: _TypeAlias = PushCaseResponse  # noqa: Y015

@_typing.final
class FileChange(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PATH_FIELD_NUMBER: _builtins.int
    CONTENT_FIELD_NUMBER: _builtins.int
    DELETE_FIELD_NUMBER: _builtins.int
    path: _builtins.str
    """Relative to the case directory, with `/` separators and no `..`."""
    content: _builtins.bytes
    """The file's new content, at most 1 MiB. Creates the file, with mode 0644, if it is new."""
    delete: _builtins.bool
    """Removes the file. Must be true."""
    def __init__(
        self,
        *,
        path: _builtins.str = ...,
        content: _builtins.bytes = ...,
        delete: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["change", b"change", "content", b"content", "delete", b"delete"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["change", b"change", "content", b"content", "delete", b"delete", "path", b"path"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_change: _TypeAlias = _typing.Literal["content", "delete"]  # noqa: Y015
    _WhichOneofArgType_change: _TypeAlias = _typing.Literal["change", b"change"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_change) -> _WhichOneofReturnType_change | None: ...

Global___FileChange: _TypeAlias = FileChange  # noqa: Y015

@_typing.final
class UpdateCaseFilesRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    WORKSPACE_FIELD_NUMBER: _builtins.int
    CASE_ID_FIELD_NUMBER: _builtins.int
    BASE_REVISION_FIELD_NUMBER: _builtins.int
    CHANGES_FIELD_NUMBER: _builtins.int
    ACTOR_FIELD_NUMBER: _builtins.int
    NOTE_FIELD_NUMBER: _builtins.int
    workspace: _builtins.str
    case_id: _builtins.str
    base_revision: _builtins.int
    """The revision the changes were made against. Zero for a case that does not exist yet."""
    actor: _builtins.str
    note: _builtins.str
    @_builtins.property
    def changes(self) -> _containers.RepeatedCompositeFieldContainer[Global___FileChange]: ...
    def __init__(
        self,
        *,
        workspace: _builtins.str = ...,
        case_id: _builtins.str = ...,
        base_revision: _builtins.int = ...,
        changes: _abc.Iterable[Global___FileChange] | None = ...,
        actor: _builtins.str = ...,
        note: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["actor", b"actor", "base_revision", b"base_revision", "case_id", b"case_id", "changes", b"changes", "note", b"note", "workspace", b"workspace"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UpdateCaseFilesRequest: _TypeAlias = UpdateCaseFilesRequest  # noqa: Y015

@_typing.final
class UpdateCaseFilesResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REVISION_FIELD_NUMBER: _builtins.int
    CREATED_FIELD_NUMBER: _builtins.int
    created: _builtins.bool
    """False when the changes left every file as it was."""
    @_builtins.property
    def revision(self) -> Global___CaseRevision: ...
    def __init__(
        self,
        *,
        revision: Global___CaseRevision | None = ...,
        created: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["revision", b"revision"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["created", b"created", "revision", b"revision"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UpdateCaseFilesResponse: _TypeAlias = UpdateCaseFilesResponse  # noqa: Y015

@_typing.final
class GetCaseRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    WORKSPACE_FIELD_NUMBER: _builtins.int
    CASE_ID_FIELD_NUMBER: _builtins.int
    workspace: _builtins.str
    case_id: _builtins.str
    def __init__(
        self,
        *,
        workspace: _builtins.str = ...,
        case_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["case_id", b"case_id", "workspace", b"workspace"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetCaseRequest: _TypeAlias = GetCaseRequest  # noqa: Y015

@_typing.final
class GetCaseResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CASE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def case(self) -> Global___Case: ...
    def __init__(
        self,
        *,
        case: Global___Case | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["case", b"case"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["case", b"case"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetCaseResponse: _TypeAlias = GetCaseResponse  # noqa: Y015

@_typing.final
class ListCasesRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    WORKSPACE_FIELD_NUMBER: _builtins.int
    INCLUDE_ARCHIVED_FIELD_NUMBER: _builtins.int
    workspace: _builtins.str
    """Empty for every workspace."""
    include_archived: _builtins.bool
    def __init__(
        self,
        *,
        workspace: _builtins.str = ...,
        include_archived: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["include_archived", b"include_archived", "workspace", b"workspace"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListCasesRequest: _TypeAlias = ListCasesRequest  # noqa: Y015

@_typing.final
class ListCasesResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CASES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def cases(self) -> _containers.RepeatedCompositeFieldContainer[Global___Case]: ...
    def __init__(
        self,
        *,
        cases: _abc.Iterable[Global___Case] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["cases", b"cases"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListCasesResponse: _TypeAlias = ListCasesResponse  # noqa: Y015

@_typing.final
class ListCaseRevisionsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    WORKSPACE_FIELD_NUMBER: _builtins.int
    CASE_ID_FIELD_NUMBER: _builtins.int
    workspace: _builtins.str
    case_id: _builtins.str
    def __init__(
        self,
        *,
        workspace: _builtins.str = ...,
        case_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["case_id", b"case_id", "workspace", b"workspace"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListCaseRevisionsRequest: _TypeAlias = ListCaseRevisionsRequest  # noqa: Y015

@_typing.final
class ListCaseRevisionsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REVISIONS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def revisions(self) -> _containers.RepeatedCompositeFieldContainer[Global___CaseRevision]: ...
    def __init__(
        self,
        *,
        revisions: _abc.Iterable[Global___CaseRevision] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["revisions", b"revisions"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListCaseRevisionsResponse: _TypeAlias = ListCaseRevisionsResponse  # noqa: Y015

@_typing.final
class GetCaseRevisionRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    WORKSPACE_FIELD_NUMBER: _builtins.int
    CASE_ID_FIELD_NUMBER: _builtins.int
    REVISION_FIELD_NUMBER: _builtins.int
    workspace: _builtins.str
    case_id: _builtins.str
    revision: _builtins.int
    """Zero means the newest."""
    def __init__(
        self,
        *,
        workspace: _builtins.str = ...,
        case_id: _builtins.str = ...,
        revision: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["case_id", b"case_id", "revision", b"revision", "workspace", b"workspace"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetCaseRevisionRequest: _TypeAlias = GetCaseRevisionRequest  # noqa: Y015

@_typing.final
class GetCaseRevisionResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REVISION_FIELD_NUMBER: _builtins.int
    FILES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def revision(self) -> Global___CaseRevision: ...
    @_builtins.property
    def files(self) -> _containers.RepeatedCompositeFieldContainer[Global___CaseFile]:
        """By path."""

    def __init__(
        self,
        *,
        revision: Global___CaseRevision | None = ...,
        files: _abc.Iterable[Global___CaseFile] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["revision", b"revision"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["files", b"files", "revision", b"revision"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetCaseRevisionResponse: _TypeAlias = GetCaseRevisionResponse  # noqa: Y015

@_typing.final
class ArchiveCaseRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    WORKSPACE_FIELD_NUMBER: _builtins.int
    CASE_ID_FIELD_NUMBER: _builtins.int
    ACTOR_FIELD_NUMBER: _builtins.int
    workspace: _builtins.str
    case_id: _builtins.str
    actor: _builtins.str
    def __init__(
        self,
        *,
        workspace: _builtins.str = ...,
        case_id: _builtins.str = ...,
        actor: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["actor", b"actor", "case_id", b"case_id", "workspace", b"workspace"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ArchiveCaseRequest: _TypeAlias = ArchiveCaseRequest  # noqa: Y015

@_typing.final
class ArchiveCaseResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CASE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def case(self) -> Global___Case: ...
    def __init__(
        self,
        *,
        case: Global___Case | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["case", b"case"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["case", b"case"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ArchiveCaseResponse: _TypeAlias = ArchiveCaseResponse  # noqa: Y015

@_typing.final
class UnarchiveCaseRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    WORKSPACE_FIELD_NUMBER: _builtins.int
    CASE_ID_FIELD_NUMBER: _builtins.int
    ACTOR_FIELD_NUMBER: _builtins.int
    workspace: _builtins.str
    case_id: _builtins.str
    actor: _builtins.str
    def __init__(
        self,
        *,
        workspace: _builtins.str = ...,
        case_id: _builtins.str = ...,
        actor: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["actor", b"actor", "case_id", b"case_id", "workspace", b"workspace"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UnarchiveCaseRequest: _TypeAlias = UnarchiveCaseRequest  # noqa: Y015

@_typing.final
class UnarchiveCaseResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CASE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def case(self) -> Global___Case: ...
    def __init__(
        self,
        *,
        case: Global___Case | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["case", b"case"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["case", b"case"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UnarchiveCaseResponse: _TypeAlias = UnarchiveCaseResponse  # noqa: Y015
