"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import struct_pb2 as _struct_pb2
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class SubmitRunsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CASE_BUNDLE_FIELD_NUMBER: _builtins.int
    OVERRIDES_FIELD_NUMBER: _builtins.int
    EPOCHS_FIELD_NUMBER: _builtins.int
    SUITE_FIELD_NUMBER: _builtins.int
    case_bundle: _builtins.bytes
    """The case directory as an uncompressed tar archive, with `case.yaml` at its root."""
    epochs: _builtins.int
    """Runs per variant. Zero means the case's `epochs`."""
    suite: _builtins.str
    """Labels the submissions of one suite run, so a report can cover them together: lowercase
    letters, digits, `_`, `.`, and `-`, starting with a letter or digit. Empty for none.
    """
    @_builtins.property
    def overrides(self) -> _struct_pb2.Struct:
        """Variant axis → list of values, replacing that axis's values in the case."""

    def __init__(
        self,
        *,
        case_bundle: _builtins.bytes = ...,
        overrides: _struct_pb2.Struct | None = ...,
        epochs: _builtins.int = ...,
        suite: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["overrides", b"overrides"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["case_bundle", b"case_bundle", "epochs", b"epochs", "overrides", b"overrides", "suite", b"suite"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SubmitRunsRequest: _TypeAlias = SubmitRunsRequest  # noqa: Y015

@_typing.final
class SubmitRunsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUBMISSION_ID_FIELD_NUMBER: _builtins.int
    RUN_IDS_FIELD_NUMBER: _builtins.int
    submission_id: _builtins.str
    @_builtins.property
    def run_ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        submission_id: _builtins.str = ...,
        run_ids: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["run_ids", b"run_ids", "submission_id", b"submission_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SubmitRunsResponse: _TypeAlias = SubmitRunsResponse  # noqa: Y015

@_typing.final
class Run(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    SUBMISSION_ID_FIELD_NUMBER: _builtins.int
    CASE_ID_FIELD_NUMBER: _builtins.int
    WORKSPACE_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    VARIANT_FIELD_NUMBER: _builtins.int
    TASK_ARGS_FIELD_NUMBER: _builtins.int
    EPOCH_FIELD_NUMBER: _builtins.int
    EPOCHS_FIELD_NUMBER: _builtins.int
    CASE_SHA256_FIELD_NUMBER: _builtins.int
    OWNER_ID_FIELD_NUMBER: _builtins.int
    ISOLATION_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    CREATED_AT_FIELD_NUMBER: _builtins.int
    STARTED_AT_FIELD_NUMBER: _builtins.int
    FINISHED_AT_FIELD_NUMBER: _builtins.int
    REPLACES_FIELD_NUMBER: _builtins.int
    SUITE_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    submission_id: _builtins.str
    case_id: _builtins.str
    workspace: _builtins.str
    status: _builtins.str
    """`queued`, `running`, `paused`, `interrupted`, `done`, `failed`, or `cancelled`."""
    variant: _builtins.int
    epoch: _builtins.int
    epochs: _builtins.int
    case_sha256: _builtins.str
    owner_id: _builtins.str
    isolation: _builtins.str
    """Container runtime the run's sandboxes got: `runc` or `runsc`. Empty until they exist."""
    error: _builtins.str
    """Why the run failed or was interrupted."""
    replaces: _builtins.str
    """The interrupted run this one reruns at a new epoch; empty for a run the submission asked for."""
    suite: _builtins.str
    """The suite label of the run's submission; empty for none."""
    @_builtins.property
    def task_args(self) -> _struct_pb2.Struct:
        """The variant's axis values."""

    @_builtins.property
    def created_at(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def started_at(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def finished_at(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
        submission_id: _builtins.str = ...,
        case_id: _builtins.str = ...,
        workspace: _builtins.str = ...,
        status: _builtins.str = ...,
        variant: _builtins.int = ...,
        task_args: _struct_pb2.Struct | None = ...,
        epoch: _builtins.int = ...,
        epochs: _builtins.int = ...,
        case_sha256: _builtins.str = ...,
        owner_id: _builtins.str = ...,
        isolation: _builtins.str = ...,
        error: _builtins.str = ...,
        created_at: _timestamp_pb2.Timestamp | None = ...,
        started_at: _timestamp_pb2.Timestamp | None = ...,
        finished_at: _timestamp_pb2.Timestamp | None = ...,
        replaces: _builtins.str = ...,
        suite: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["created_at", b"created_at", "finished_at", b"finished_at", "started_at", b"started_at", "task_args", b"task_args"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["case_id", b"case_id", "case_sha256", b"case_sha256", "created_at", b"created_at", "epoch", b"epoch", "epochs", b"epochs", "error", b"error", "finished_at", b"finished_at", "isolation", b"isolation", "owner_id", b"owner_id", "replaces", b"replaces", "run_id", b"run_id", "started_at", b"started_at", "status", b"status", "submission_id", b"submission_id", "suite", b"suite", "task_args", b"task_args", "variant", b"variant", "workspace", b"workspace"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Run: _TypeAlias = Run  # noqa: Y015

@_typing.final
class GetRunRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["run_id", b"run_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetRunRequest: _TypeAlias = GetRunRequest  # noqa: Y015

@_typing.final
class GetRunResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def run(self) -> Global___Run: ...
    def __init__(
        self,
        *,
        run: Global___Run | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["run", b"run"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["run", b"run"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetRunResponse: _TypeAlias = GetRunResponse  # noqa: Y015

@_typing.final
class ListRunsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUBMISSION_ID_FIELD_NUMBER: _builtins.int
    CASE_ID_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    SUITE_FIELD_NUMBER: _builtins.int
    LIMIT_FIELD_NUMBER: _builtins.int
    submission_id: _builtins.str
    """Filters; empty matches everything."""
    case_id: _builtins.str
    status: _builtins.str
    suite: _builtins.str
    limit: _builtins.int
    """Zero means 100."""
    def __init__(
        self,
        *,
        submission_id: _builtins.str = ...,
        case_id: _builtins.str = ...,
        status: _builtins.str = ...,
        suite: _builtins.str = ...,
        limit: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["case_id", b"case_id", "limit", b"limit", "status", b"status", "submission_id", b"submission_id", "suite", b"suite"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListRunsRequest: _TypeAlias = ListRunsRequest  # noqa: Y015

@_typing.final
class ListRunsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUNS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def runs(self) -> _containers.RepeatedCompositeFieldContainer[Global___Run]: ...
    def __init__(
        self,
        *,
        runs: _abc.Iterable[Global___Run] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["runs", b"runs"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListRunsResponse: _TypeAlias = ListRunsResponse  # noqa: Y015

@_typing.final
class CancelRunRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["run_id", b"run_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CancelRunRequest: _TypeAlias = CancelRunRequest  # noqa: Y015

@_typing.final
class CancelRunResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def run(self) -> Global___Run: ...
    def __init__(
        self,
        *,
        run: Global___Run | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["run", b"run"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["run", b"run"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CancelRunResponse: _TypeAlias = CancelRunResponse  # noqa: Y015

@_typing.final
class StreamEventsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    AFTER_SEQ_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    after_seq: _builtins.int
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
        after_seq: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["after_seq", b"after_seq", "run_id", b"run_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StreamEventsRequest: _TypeAlias = StreamEventsRequest  # noqa: Y015

@_typing.final
class StreamEventsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SEQ_FIELD_NUMBER: _builtins.int
    EVENT_ID_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    AGENT_ID_FIELD_NUMBER: _builtins.int
    PAYLOAD_JSON_FIELD_NUMBER: _builtins.int
    seq: _builtins.int
    event_id: _builtins.str
    type: _builtins.str
    """The Inspect event type, or an InfoEvent's `swarmeval.<kind>` source."""
    agent_id: _builtins.str
    payload_json: _builtins.str
    """The stored Inspect event, as JSON."""
    def __init__(
        self,
        *,
        seq: _builtins.int = ...,
        event_id: _builtins.str = ...,
        type: _builtins.str = ...,
        agent_id: _builtins.str = ...,
        payload_json: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["agent_id", b"agent_id", "event_id", b"event_id", "payload_json", b"payload_json", "seq", b"seq", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StreamEventsResponse: _TypeAlias = StreamEventsResponse  # noqa: Y015
