"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
from swarmeval.proto.swarmeval.control.v1 import control_pb2 as _control_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class ControlServiceStub:
    """ControlService is the orchestrator control plane's API. Until edge exists (M4) it is bound to
    the internal network and has no authentication. Behavior: docs/services/orchestrator.md.
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> ControlServiceAsyncStub: ...
    SubmitRuns: _grpc.UnaryUnaryMultiCallable[_control_pb2.SubmitRunsRequest, _control_pb2.SubmitRunsResponse]
    """Validates a case bundle, stores it by hash, and queues one run per variant and epoch.
    A case that does not load is INVALID_ARGUMENT, with the loader's message.
    """
    SubmitSuite: _grpc.UnaryUnaryMultiCallable[_control_pb2.SubmitSuiteRequest, _control_pb2.SubmitSuiteResponse]
    """Loads a suite with the case bundles it names and queues every case's runs in one
    transaction, each case its own submission under one suite label: a suite with a case that
    does not load queues nothing. The format: docs/case-format.md#suites. INVALID_ARGUMENT names
    the suite entry at fault.
    """
    GetRun: _grpc.UnaryUnaryMultiCallable[_control_pb2.GetRunRequest, _control_pb2.GetRunResponse]
    ListRuns: _grpc.UnaryUnaryMultiCallable[_control_pb2.ListRunsRequest, _control_pb2.ListRunsResponse]
    """Newest first."""
    CancelRun: _grpc.UnaryUnaryMultiCallable[_control_pb2.CancelRunRequest, _control_pb2.CancelRunResponse]
    """A queued run never starts; a running one stops at its owner's next step, keeps its events,
    and is not scored. Cancelling a finished run is FAILED_PRECONDITION.
    """
    ResumeRun: _grpc.UnaryUnaryMultiCallable[_control_pb2.ResumeRunRequest, _control_pb2.ResumeRunResponse]
    """A run paused for a person (a Monitor's `pause`) goes on from where it stopped. A run that is
    not paused is FAILED_PRECONDITION.
    """
    ForkRun: _grpc.UnaryUnaryMultiCallable[_control_pb2.ForkRunRequest, _control_pb2.ForkRunResponse]
    """A new run that goes on from a finished run's state at the start of the turn `at_event_id`
    happened in, with `edits` applied: the same case
    revision, variant, and seed, its sandboxes restored from the stored file contents. Not an
    epoch: reports keep forks apart. An unknown run or event is NOT_FOUND; a run still going, an
    event before the first turn, or an edit that does not fit the state there is
    FAILED_PRECONDITION.
    """
    StreamEvents: _grpc.UnaryStreamMultiCallable[_control_pb2.StreamEventsRequest, _control_pb2.StreamEventsResponse]
    """A run's events with seq greater than `after_seq`, live while the run is going. The stream
    ends once the run has finished and every event was sent.
    """

@_typing.type_check_only
class ControlServiceAsyncStub(ControlServiceStub):
    """ControlService is the orchestrator control plane's API. Until edge exists (M4) it is bound to
    the internal network and has no authentication. Behavior: docs/services/orchestrator.md.
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    SubmitRuns: _aio.UnaryUnaryMultiCallable[_control_pb2.SubmitRunsRequest, _control_pb2.SubmitRunsResponse]  # type: ignore[assignment]
    """Validates a case bundle, stores it by hash, and queues one run per variant and epoch.
    A case that does not load is INVALID_ARGUMENT, with the loader's message.
    """
    SubmitSuite: _aio.UnaryUnaryMultiCallable[_control_pb2.SubmitSuiteRequest, _control_pb2.SubmitSuiteResponse]  # type: ignore[assignment]
    """Loads a suite with the case bundles it names and queues every case's runs in one
    transaction, each case its own submission under one suite label: a suite with a case that
    does not load queues nothing. The format: docs/case-format.md#suites. INVALID_ARGUMENT names
    the suite entry at fault.
    """
    GetRun: _aio.UnaryUnaryMultiCallable[_control_pb2.GetRunRequest, _control_pb2.GetRunResponse]  # type: ignore[assignment]
    ListRuns: _aio.UnaryUnaryMultiCallable[_control_pb2.ListRunsRequest, _control_pb2.ListRunsResponse]  # type: ignore[assignment]
    """Newest first."""
    CancelRun: _aio.UnaryUnaryMultiCallable[_control_pb2.CancelRunRequest, _control_pb2.CancelRunResponse]  # type: ignore[assignment]
    """A queued run never starts; a running one stops at its owner's next step, keeps its events,
    and is not scored. Cancelling a finished run is FAILED_PRECONDITION.
    """
    ResumeRun: _aio.UnaryUnaryMultiCallable[_control_pb2.ResumeRunRequest, _control_pb2.ResumeRunResponse]  # type: ignore[assignment]
    """A run paused for a person (a Monitor's `pause`) goes on from where it stopped. A run that is
    not paused is FAILED_PRECONDITION.
    """
    ForkRun: _aio.UnaryUnaryMultiCallable[_control_pb2.ForkRunRequest, _control_pb2.ForkRunResponse]  # type: ignore[assignment]
    """A new run that goes on from a finished run's state at the start of the turn `at_event_id`
    happened in, with `edits` applied: the same case
    revision, variant, and seed, its sandboxes restored from the stored file contents. Not an
    epoch: reports keep forks apart. An unknown run or event is NOT_FOUND; a run still going, an
    event before the first turn, or an edit that does not fit the state there is
    FAILED_PRECONDITION.
    """
    StreamEvents: _aio.UnaryStreamMultiCallable[_control_pb2.StreamEventsRequest, _control_pb2.StreamEventsResponse]  # type: ignore[assignment]
    """A run's events with seq greater than `after_seq`, live while the run is going. The stream
    ends once the run has finished and every event was sent.
    """

class ControlServiceServicer(metaclass=_abc_1.ABCMeta):
    """ControlService is the orchestrator control plane's API. Until edge exists (M4) it is bound to
    the internal network and has no authentication. Behavior: docs/services/orchestrator.md.
    """

    @_abc_1.abstractmethod
    def SubmitRuns(
        self,
        request: _control_pb2.SubmitRunsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_control_pb2.SubmitRunsResponse, _abc.Awaitable[_control_pb2.SubmitRunsResponse]]:
        """Validates a case bundle, stores it by hash, and queues one run per variant and epoch.
        A case that does not load is INVALID_ARGUMENT, with the loader's message.
        """

    @_abc_1.abstractmethod
    def SubmitSuite(
        self,
        request: _control_pb2.SubmitSuiteRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_control_pb2.SubmitSuiteResponse, _abc.Awaitable[_control_pb2.SubmitSuiteResponse]]:
        """Loads a suite with the case bundles it names and queues every case's runs in one
        transaction, each case its own submission under one suite label: a suite with a case that
        does not load queues nothing. The format: docs/case-format.md#suites. INVALID_ARGUMENT names
        the suite entry at fault.
        """

    @_abc_1.abstractmethod
    def GetRun(
        self,
        request: _control_pb2.GetRunRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_control_pb2.GetRunResponse, _abc.Awaitable[_control_pb2.GetRunResponse]]: ...

    @_abc_1.abstractmethod
    def ListRuns(
        self,
        request: _control_pb2.ListRunsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_control_pb2.ListRunsResponse, _abc.Awaitable[_control_pb2.ListRunsResponse]]:
        """Newest first."""

    @_abc_1.abstractmethod
    def CancelRun(
        self,
        request: _control_pb2.CancelRunRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_control_pb2.CancelRunResponse, _abc.Awaitable[_control_pb2.CancelRunResponse]]:
        """A queued run never starts; a running one stops at its owner's next step, keeps its events,
        and is not scored. Cancelling a finished run is FAILED_PRECONDITION.
        """

    @_abc_1.abstractmethod
    def ResumeRun(
        self,
        request: _control_pb2.ResumeRunRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_control_pb2.ResumeRunResponse, _abc.Awaitable[_control_pb2.ResumeRunResponse]]:
        """A run paused for a person (a Monitor's `pause`) goes on from where it stopped. A run that is
        not paused is FAILED_PRECONDITION.
        """

    @_abc_1.abstractmethod
    def ForkRun(
        self,
        request: _control_pb2.ForkRunRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_control_pb2.ForkRunResponse, _abc.Awaitable[_control_pb2.ForkRunResponse]]:
        """A new run that goes on from a finished run's state at the start of the turn `at_event_id`
        happened in, with `edits` applied: the same case
        revision, variant, and seed, its sandboxes restored from the stored file contents. Not an
        epoch: reports keep forks apart. An unknown run or event is NOT_FOUND; a run still going, an
        event before the first turn, or an edit that does not fit the state there is
        FAILED_PRECONDITION.
        """

    @_abc_1.abstractmethod
    def StreamEvents(
        self,
        request: _control_pb2.StreamEventsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_control_pb2.StreamEventsResponse], _abc.AsyncIterator[_control_pb2.StreamEventsResponse]]:
        """A run's events with seq greater than `after_seq`, live while the run is going. The stream
        ends once the run has finished and every event was sent.
        """

def add_ControlServiceServicer_to_server(servicer: ControlServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
