# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from swarmeval.proto.swarmeval.control.v1 import control_pb2 as swarmeval_dot_proto_dot_swarmeval_dot_control_dot_v1_dot_control__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in swarmeval/proto/swarmeval/control/v1/control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ControlServiceStub:
    """ControlService is the orchestrator control plane's API. Until edge exists (M4) it is bound to
    the internal network and has no authentication. Behavior: docs/services/orchestrator.md.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitRuns = channel.unary_unary(
                '/swarmeval.control.v1.ControlService/SubmitRuns',
                request_serializer=swarmeval_dot_proto_dot_swarmeval_dot_control_dot_v1_dot_control__pb2.SubmitRunsRequest.SerializeToString,
                response_deserializer=swarmeval_dot_proto_dot_swarmeval_dot_control_dot_v1_dot_control__pb2.SubmitRunsResponse.FromString,
                _registered_method=True)
        self.SubmitSuite = channel.unary_unary(
                '/swarmeval.control.v1.ControlService/SubmitSuite',
                request_serializer=swarmeval_dot_proto_dot_swarmeval_dot_control_dot_v1_dot_control__pb2.SubmitSuiteRequest.SerializeToString,
                response_deserializer=swarmeval_dot_proto_dot_swarmeval_dot_control_dot_v1_dot_control__pb2.SubmitSuiteResponse.FromString,
                _registered_method=True)
        self.GetRun = channel.unary_unary(
                '/swarmeval.control.v1.ControlService/GetRun',
                request_serializer=swarmeval_dot_proto_dot_swarmeval_dot_control_dot_v1_dot_control__pb2.GetRunRequest.SerializeToString,
                response_deserializer=swarmeval_dot_proto_dot_swarmeval_dot_control_dot_v1_dot_control__pb2.GetRunResponse.FromString,
                _registered_method=True)
        self.ListRuns = channel.unary_unary(
                '/swarmeval.control.v1.ControlService/ListRuns',
                request_serializer=swarmeval_dot_proto_dot_swarmeval_dot_control_dot_v1_dot_control__pb2.ListRunsRequest.SerializeToString,
                response_deserializer=swarmeval_dot_proto_dot_swarmeval_dot_control_dot_v1_dot_control__pb2.ListRunsResponse.FromString,
                _registered_method=True)
        self.CancelRun = channel.unary_unary(
                '/swarmeval.control.v1.ControlService/CancelRun',
                request_serializer=swarmeval_dot_proto_dot_swarmeval_dot_control_dot_v1_dot_control__pb2.CancelRunRequest.SerializeToString,
                response_deserializer=swarmeval_dot_proto_dot_swarmeval_dot_control_dot_v1_dot_control__pb2.CancelRunResponse.FromString,
                _registered_method=True)
        self.ResumeRun = channel.unary_unary(
                '/swarmeval.control.v1.ControlService/ResumeRun',
                request_serializer=swarmeval_dot_proto_dot_swarmeval_dot_control_dot_v1_dot_control__pb2.ResumeRunRequest.SerializeToString,
                response_deserializer=swarmeval_dot_proto_dot_swarmeval_dot_control_dot_v1_dot_control__pb2.ResumeRunResponse.FromString,
                _registered_method=True)
        self.ForkRun = channel.unary_unary(
                '/swarmeval.control.v1.ControlService/ForkRun',
                request_serializer=swarmeval_dot_proto_dot_swarmeval_dot_control_dot_v1_dot_control__pb2.ForkRunRequest.SerializeToString,
                response_deserializer=swarmeval_dot_proto_dot_swarmeval_dot_control_dot_v1_dot_control__pb2.ForkRunResponse.FromString,
                _registered_method=True)
        self.StreamEvents = channel.unary_stream(
                '/swarmeval.control.v1.ControlService/StreamEvents',
                request_serializer=swarmeval_dot_proto_dot_swarmeval_dot_control_dot_v1_dot_control__pb2.StreamEventsRequest.SerializeToString,
                response_deserializer=swarmeval_dot_proto_dot_swarmeval_dot_control_dot_v1_dot_control__pb2.StreamEventsResponse.FromString,
                _registered_method=True)


class ControlServiceServicer:
    """ControlService is the orchestrator control plane's API. Until edge exists (M4) it is bound to
    the internal network and has no authentication. Behavior: docs/services/orchestrator.md.
    """

    def SubmitRuns(self, request, context):
        """Validates a case bundle, stores it by hash, and queues one run per variant and epoch.
        A case that does not load is INVALID_ARGUMENT, with the loader's message.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitSuite(self, request, context):
        """Loads a suite with the case bundles it names and queues every case's runs in one
        transaction, each case its own submission under one suite label: a suite with a case that
        does not load queues nothing. The format: docs/case-format.md#suites. INVALID_ARGUMENT names
        the suite entry at fault.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRuns(self, request, context):
        """Newest first.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelRun(self, request, context):
        """A queued run never starts; a running one stops at its owner's next step, keeps its events,
        and is not scored. Cancelling a finished run is FAILED_PRECONDITION.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeRun(self, request, context):
        """A run paused for a person (a Monitor's `pause`) goes on from where it stopped. A run that is
        not paused is FAILED_PRECONDITION.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ForkRun(self, request, context):
        """A new run that goes on from a finished run's state at the start of the turn `at_event_id`
        happened in, with `edits` applied: the same case
        revision, variant, and seed, its sandboxes restored from the stored file contents. Not an
        epoch: reports keep forks apart. An unknown run or event is NOT_FOUND; a run still going, an
        event before the first turn, or an edit that does not fit the state there is
        FAILED_PRECONDITION.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamEvents(self, request, context):
        """A run's events with seq greater than `after_seq`, live while the run is going. The stream
        ends once the run has finished and every event was sent.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitRuns': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitRuns,
                    request_deserializer=swarmeval_dot_proto_dot_swarmeval_dot_control_dot_v1_dot_control__pb2.SubmitRunsRequest.FromString,
                    response_serializer=swarmeval_dot_proto_dot_swarmeval_dot_control_dot_v1_dot_control__pb2.SubmitRunsResponse.SerializeToString,
            ),
            'SubmitSuite': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitSuite,
                    request_deserializer=swarmeval_dot_proto_dot_swarmeval_dot_control_dot_v1_dot_control__pb2.SubmitSuiteRequest.FromString,
                    response_serializer=swarmeval_dot_proto_dot_swarmeval_dot_control_dot_v1_dot_control__pb2.SubmitSuiteResponse.SerializeToString,
            ),
            'GetRun': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRun,
                    request_deserializer=swarmeval_dot_proto_dot_swarmeval_dot_control_dot_v1_dot_control__pb2.GetRunRequest.FromString,
                    response_serializer=swarmeval_dot_proto_dot_swarmeval_dot_control_dot_v1_dot_control__pb2.GetRunResponse.SerializeToString,
            ),
            'ListRuns': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRuns,
                    request_deserializer=swarmeval_dot_proto_dot_swarmeval_dot_control_dot_v1_dot_control__pb2.ListRunsRequest.FromString,
                    response_serializer=swarmeval_dot_proto_dot_swarmeval_dot_control_dot_v1_dot_control__pb2.ListRunsResponse.SerializeToString,
            ),
            'CancelRun': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelRun,
                    request_deserializer=swarmeval_dot_proto_dot_swarmeval_dot_control_dot_v1_dot_control__pb2.CancelRunRequest.FromString,
                    response_serializer=swarmeval_dot_proto_dot_swarmeval_dot_control_dot_v1_dot_control__pb2.CancelRunResponse.SerializeToString,
            ),
            'ResumeRun': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeRun,
                    request_deserializer=swarmeval_dot_proto_dot_swarmeval_dot_control_dot_v1_dot_control__pb2.ResumeRunRequest.FromString,
                    response_serializer=swarmeval_dot_proto_dot_swarmeval_dot_control_dot_v1_dot_control__pb2.ResumeRunResponse.SerializeToString,
            ),
            'ForkRun': grpc.unary_unary_rpc_method_handler(
                    servicer.ForkRun,
                    request_deserializer=swarmeval_dot_proto_dot_swarmeval_dot_control_dot_v1_dot_control__pb2.ForkRunRequest.FromString,
                    response_serializer=swarmeval_dot_proto_dot_swarmeval_dot_control_dot_v1_dot_control__pb2.ForkRunResponse.SerializeToString,
            ),
            'StreamEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamEvents,
                    request_deserializer=swarmeval_dot_proto_dot_swarmeval_dot_control_dot_v1_dot_control__pb2.StreamEventsRequest.FromString,
                    response_serializer=swarmeval_dot_proto_dot_swarmeval_dot_control_dot_v1_dot_control__pb2.StreamEventsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swarmeval.control.v1.ControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('swarmeval.control.v1.ControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ControlService:
    """ControlService is the orchestrator control plane's API. Until edge exists (M4) it is bound to
    the internal network and has no authentication. Behavior: docs/services/orchestrator.md.
    """

    @staticmethod
    def SubmitRuns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swarmeval.control.v1.ControlService/SubmitRuns',
            swarmeval_dot_proto_dot_swarmeval_dot_control_dot_v1_dot_control__pb2.SubmitRunsRequest.SerializeToString,
            swarmeval_dot_proto_dot_swarmeval_dot_control_dot_v1_dot_control__pb2.SubmitRunsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitSuite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swarmeval.control.v1.ControlService/SubmitSuite',
            swarmeval_dot_proto_dot_swarmeval_dot_control_dot_v1_dot_control__pb2.SubmitSuiteRequest.SerializeToString,
            swarmeval_dot_proto_dot_swarmeval_dot_control_dot_v1_dot_control__pb2.SubmitSuiteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swarmeval.control.v1.ControlService/GetRun',
            swarmeval_dot_proto_dot_swarmeval_dot_control_dot_v1_dot_control__pb2.GetRunRequest.SerializeToString,
            swarmeval_dot_proto_dot_swarmeval_dot_control_dot_v1_dot_control__pb2.GetRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRuns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swarmeval.control.v1.ControlService/ListRuns',
            swarmeval_dot_proto_dot_swarmeval_dot_control_dot_v1_dot_control__pb2.ListRunsRequest.SerializeToString,
            swarmeval_dot_proto_dot_swarmeval_dot_control_dot_v1_dot_control__pb2.ListRunsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swarmeval.control.v1.ControlService/CancelRun',
            swarmeval_dot_proto_dot_swarmeval_dot_control_dot_v1_dot_control__pb2.CancelRunRequest.SerializeToString,
            swarmeval_dot_proto_dot_swarmeval_dot_control_dot_v1_dot_control__pb2.CancelRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swarmeval.control.v1.ControlService/ResumeRun',
            swarmeval_dot_proto_dot_swarmeval_dot_control_dot_v1_dot_control__pb2.ResumeRunRequest.SerializeToString,
            swarmeval_dot_proto_dot_swarmeval_dot_control_dot_v1_dot_control__pb2.ResumeRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ForkRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swarmeval.control.v1.ControlService/ForkRun',
            swarmeval_dot_proto_dot_swarmeval_dot_control_dot_v1_dot_control__pb2.ForkRunRequest.SerializeToString,
            swarmeval_dot_proto_dot_swarmeval_dot_control_dot_v1_dot_control__pb2.ForkRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/swarmeval.control.v1.ControlService/StreamEvents',
            swarmeval_dot_proto_dot_swarmeval_dot_control_dot_v1_dot_control__pb2.StreamEventsRequest.SerializeToString,
            swarmeval_dot_proto_dot_swarmeval_dot_control_dot_v1_dot_control__pb2.StreamEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
