# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from swarmeval.proto.swarmeval.sandbox.v1 import sandbox_pb2 as swarmeval_dot_proto_dot_swarmeval_dot_sandbox_dot_v1_dot_sandbox__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in swarmeval/proto/swarmeval/sandbox/v1/sandbox_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SandboxServiceStub:
    """SandboxService is sandboxd's API. Its only caller is the worker that owns the run.
    Behavior: docs/services/sandboxd.md.

    Identifiers: `run_id` matches [A-Za-z0-9][A-Za-z0-9._-]{0,127}; `sandbox_id` matches
    [a-z][a-z0-9_]{0,62} (the case format's names). Anything else is INVALID_ARGUMENT.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateRun = channel.unary_unary(
                '/swarmeval.sandbox.v1.SandboxService/CreateRun',
                request_serializer=swarmeval_dot_proto_dot_swarmeval_dot_sandbox_dot_v1_dot_sandbox__pb2.CreateRunRequest.SerializeToString,
                response_deserializer=swarmeval_dot_proto_dot_swarmeval_dot_sandbox_dot_v1_dot_sandbox__pb2.CreateRunResponse.FromString,
                _registered_method=True)
        self.CreateSandbox = channel.unary_unary(
                '/swarmeval.sandbox.v1.SandboxService/CreateSandbox',
                request_serializer=swarmeval_dot_proto_dot_swarmeval_dot_sandbox_dot_v1_dot_sandbox__pb2.CreateSandboxRequest.SerializeToString,
                response_deserializer=swarmeval_dot_proto_dot_swarmeval_dot_sandbox_dot_v1_dot_sandbox__pb2.CreateSandboxResponse.FromString,
                _registered_method=True)
        self.Exec = channel.unary_stream(
                '/swarmeval.sandbox.v1.SandboxService/Exec',
                request_serializer=swarmeval_dot_proto_dot_swarmeval_dot_sandbox_dot_v1_dot_sandbox__pb2.ExecRequest.SerializeToString,
                response_deserializer=swarmeval_dot_proto_dot_swarmeval_dot_sandbox_dot_v1_dot_sandbox__pb2.ExecResponse.FromString,
                _registered_method=True)
        self.ReadFile = channel.unary_unary(
                '/swarmeval.sandbox.v1.SandboxService/ReadFile',
                request_serializer=swarmeval_dot_proto_dot_swarmeval_dot_sandbox_dot_v1_dot_sandbox__pb2.ReadFileRequest.SerializeToString,
                response_deserializer=swarmeval_dot_proto_dot_swarmeval_dot_sandbox_dot_v1_dot_sandbox__pb2.ReadFileResponse.FromString,
                _registered_method=True)
        self.FinalDiff = channel.unary_stream(
                '/swarmeval.sandbox.v1.SandboxService/FinalDiff',
                request_serializer=swarmeval_dot_proto_dot_swarmeval_dot_sandbox_dot_v1_dot_sandbox__pb2.FinalDiffRequest.SerializeToString,
                response_deserializer=swarmeval_dot_proto_dot_swarmeval_dot_sandbox_dot_v1_dot_sandbox__pb2.FinalDiffResponse.FromString,
                _registered_method=True)
        self.DestroyRun = channel.unary_unary(
                '/swarmeval.sandbox.v1.SandboxService/DestroyRun',
                request_serializer=swarmeval_dot_proto_dot_swarmeval_dot_sandbox_dot_v1_dot_sandbox__pb2.DestroyRunRequest.SerializeToString,
                response_deserializer=swarmeval_dot_proto_dot_swarmeval_dot_sandbox_dot_v1_dot_sandbox__pb2.DestroyRunResponse.FromString,
                _registered_method=True)


class SandboxServiceServicer:
    """SandboxService is sandboxd's API. Its only caller is the worker that owns the run.
    Behavior: docs/services/sandboxd.md.

    Identifiers: `run_id` matches [A-Za-z0-9][A-Za-z0-9._-]{0,127}; `sandbox_id` matches
    [a-z][a-z0-9_]{0,62} (the case format's names). Anything else is INVALID_ARGUMENT.
    """

    def CreateRun(self, request, context):
        """Creates a run's networks: one per sandbox, on which the host has no address. Must come
        before the run's CreateSandbox calls. Fails with ALREADY_EXISTS if the run exists.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSandbox(self, request, context):
        """Creates and starts one sandbox on its network, made by CreateRun. Each top-level key path starts as a copy of the image's
        content at that path, plus any seed files. Fails with ALREADY_EXISTS if the sandbox exists.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Exec(self, request, context):
        """Runs one tool call. The stream carries exactly one header first, then the blobs the
        header refers to, each as one or more chunks. Calls on one sandbox run one at a time.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadFile(self, request, context):
        """Reads one file from a sandbox without running anything inside it. For final-state scorers.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FinalDiff(self, request, context):
        """Diffs every sandbox of a run against its last manifest, catching writes by background
        processes after the last call. Every change is attributed `AMBIGUOUS`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DestroyRun(self, request, context):
        """Removes every container and network labeled with the run, and the run's state directory.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SandboxServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateRun': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRun,
                    request_deserializer=swarmeval_dot_proto_dot_swarmeval_dot_sandbox_dot_v1_dot_sandbox__pb2.CreateRunRequest.FromString,
                    response_serializer=swarmeval_dot_proto_dot_swarmeval_dot_sandbox_dot_v1_dot_sandbox__pb2.CreateRunResponse.SerializeToString,
            ),
            'CreateSandbox': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSandbox,
                    request_deserializer=swarmeval_dot_proto_dot_swarmeval_dot_sandbox_dot_v1_dot_sandbox__pb2.CreateSandboxRequest.FromString,
                    response_serializer=swarmeval_dot_proto_dot_swarmeval_dot_sandbox_dot_v1_dot_sandbox__pb2.CreateSandboxResponse.SerializeToString,
            ),
            'Exec': grpc.unary_stream_rpc_method_handler(
                    servicer.Exec,
                    request_deserializer=swarmeval_dot_proto_dot_swarmeval_dot_sandbox_dot_v1_dot_sandbox__pb2.ExecRequest.FromString,
                    response_serializer=swarmeval_dot_proto_dot_swarmeval_dot_sandbox_dot_v1_dot_sandbox__pb2.ExecResponse.SerializeToString,
            ),
            'ReadFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadFile,
                    request_deserializer=swarmeval_dot_proto_dot_swarmeval_dot_sandbox_dot_v1_dot_sandbox__pb2.ReadFileRequest.FromString,
                    response_serializer=swarmeval_dot_proto_dot_swarmeval_dot_sandbox_dot_v1_dot_sandbox__pb2.ReadFileResponse.SerializeToString,
            ),
            'FinalDiff': grpc.unary_stream_rpc_method_handler(
                    servicer.FinalDiff,
                    request_deserializer=swarmeval_dot_proto_dot_swarmeval_dot_sandbox_dot_v1_dot_sandbox__pb2.FinalDiffRequest.FromString,
                    response_serializer=swarmeval_dot_proto_dot_swarmeval_dot_sandbox_dot_v1_dot_sandbox__pb2.FinalDiffResponse.SerializeToString,
            ),
            'DestroyRun': grpc.unary_unary_rpc_method_handler(
                    servicer.DestroyRun,
                    request_deserializer=swarmeval_dot_proto_dot_swarmeval_dot_sandbox_dot_v1_dot_sandbox__pb2.DestroyRunRequest.FromString,
                    response_serializer=swarmeval_dot_proto_dot_swarmeval_dot_sandbox_dot_v1_dot_sandbox__pb2.DestroyRunResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swarmeval.sandbox.v1.SandboxService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('swarmeval.sandbox.v1.SandboxService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SandboxService:
    """SandboxService is sandboxd's API. Its only caller is the worker that owns the run.
    Behavior: docs/services/sandboxd.md.

    Identifiers: `run_id` matches [A-Za-z0-9][A-Za-z0-9._-]{0,127}; `sandbox_id` matches
    [a-z][a-z0-9_]{0,62} (the case format's names). Anything else is INVALID_ARGUMENT.
    """

    @staticmethod
    def CreateRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swarmeval.sandbox.v1.SandboxService/CreateRun',
            swarmeval_dot_proto_dot_swarmeval_dot_sandbox_dot_v1_dot_sandbox__pb2.CreateRunRequest.SerializeToString,
            swarmeval_dot_proto_dot_swarmeval_dot_sandbox_dot_v1_dot_sandbox__pb2.CreateRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSandbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swarmeval.sandbox.v1.SandboxService/CreateSandbox',
            swarmeval_dot_proto_dot_swarmeval_dot_sandbox_dot_v1_dot_sandbox__pb2.CreateSandboxRequest.SerializeToString,
            swarmeval_dot_proto_dot_swarmeval_dot_sandbox_dot_v1_dot_sandbox__pb2.CreateSandboxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Exec(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/swarmeval.sandbox.v1.SandboxService/Exec',
            swarmeval_dot_proto_dot_swarmeval_dot_sandbox_dot_v1_dot_sandbox__pb2.ExecRequest.SerializeToString,
            swarmeval_dot_proto_dot_swarmeval_dot_sandbox_dot_v1_dot_sandbox__pb2.ExecResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swarmeval.sandbox.v1.SandboxService/ReadFile',
            swarmeval_dot_proto_dot_swarmeval_dot_sandbox_dot_v1_dot_sandbox__pb2.ReadFileRequest.SerializeToString,
            swarmeval_dot_proto_dot_swarmeval_dot_sandbox_dot_v1_dot_sandbox__pb2.ReadFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FinalDiff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/swarmeval.sandbox.v1.SandboxService/FinalDiff',
            swarmeval_dot_proto_dot_swarmeval_dot_sandbox_dot_v1_dot_sandbox__pb2.FinalDiffRequest.SerializeToString,
            swarmeval_dot_proto_dot_swarmeval_dot_sandbox_dot_v1_dot_sandbox__pb2.FinalDiffResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DestroyRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swarmeval.sandbox.v1.SandboxService/DestroyRun',
            swarmeval_dot_proto_dot_swarmeval_dot_sandbox_dot_v1_dot_sandbox__pb2.DestroyRunRequest.SerializeToString,
            swarmeval_dot_proto_dot_swarmeval_dot_sandbox_dot_v1_dot_sandbox__pb2.DestroyRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
