"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import duration_pb2 as _duration_pb2
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class CreateRunRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    SANDBOX_IDS_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    @_builtins.property
    def sandbox_ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Every sandbox the run will create, each getting its own network."""

    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
        sandbox_ids: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["run_id", b"run_id", "sandbox_ids", b"sandbox_ids"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CreateRunRequest: _TypeAlias = CreateRunRequest  # noqa: Y015

@_typing.final
class CreateRunResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CreateRunResponse: _TypeAlias = CreateRunResponse  # noqa: Y015

@_typing.final
class Mount(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PATH_FIELD_NUMBER: _builtins.int
    READ_ONLY_FIELD_NUMBER: _builtins.int
    PROTECTED_FIELD_NUMBER: _builtins.int
    path: _builtins.str
    """Absolute path inside the sandbox."""
    read_only: _builtins.bool
    protected: _builtins.bool
    """Changes under a protected path are flagged on the change itself."""
    def __init__(
        self,
        *,
        path: _builtins.str = ...,
        read_only: _builtins.bool = ...,
        protected: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["path", b"path", "protected", b"protected", "read_only", b"read_only"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Mount: _TypeAlias = Mount  # noqa: Y015

@_typing.final
class Resources(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CPUS_FIELD_NUMBER: _builtins.int
    MEMORY_BYTES_FIELD_NUMBER: _builtins.int
    PIDS_FIELD_NUMBER: _builtins.int
    DISK_BYTES_FIELD_NUMBER: _builtins.int
    cpus: _builtins.float
    """Zero means no limit, for every field."""
    memory_bytes: _builtins.int
    pids: _builtins.int
    disk_bytes: _builtins.int
    """Needs a docker storage driver that supports a per-container size; CreateSandbox fails
    otherwise.
    """
    def __init__(
        self,
        *,
        cpus: _builtins.float = ...,
        memory_bytes: _builtins.int = ...,
        pids: _builtins.int = ...,
        disk_bytes: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["cpus", b"cpus", "disk_bytes", b"disk_bytes", "memory_bytes", b"memory_bytes", "pids", b"pids"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Resources: _TypeAlias = Resources  # noqa: Y015

@_typing.final
class CreateSandboxRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    SANDBOX_ID_FIELD_NUMBER: _builtins.int
    IMAGE_FIELD_NUMBER: _builtins.int
    MOUNTS_FIELD_NUMBER: _builtins.int
    RESOURCES_FIELD_NUMBER: _builtins.int
    FILES_FIELD_NUMBER: _builtins.int
    USERS_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    sandbox_id: _builtins.str
    image: _builtins.str
    @_builtins.property
    def mounts(self) -> _containers.RepeatedCompositeFieldContainer[Global___Mount]:
        """Key paths, bind-mounted from sandboxd's state directory and diffed after every call."""

    @_builtins.property
    def resources(self) -> Global___Resources: ...
    @_builtins.property
    def files(self) -> _containers.RepeatedCompositeFieldContainer[Global___SeedFile]:
        """Written into key paths after the image's content is copied and before the first manifest,
        so they are part of the baseline and never reported as a change. For per-run content such
        as canaries.
        """

    @_builtins.property
    def users(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Unix users to add before the sandbox starts, each with a home directory under /home. A
        name the image already has is left as it is. Names match [a-z_][a-z0-9_-]{0,31}.
        """

    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
        sandbox_id: _builtins.str = ...,
        image: _builtins.str = ...,
        mounts: _abc.Iterable[Global___Mount] | None = ...,
        resources: Global___Resources | None = ...,
        files: _abc.Iterable[Global___SeedFile] | None = ...,
        users: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["resources", b"resources"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["files", b"files", "image", b"image", "mounts", b"mounts", "resources", b"resources", "run_id", b"run_id", "sandbox_id", b"sandbox_id", "users", b"users"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CreateSandboxRequest: _TypeAlias = CreateSandboxRequest  # noqa: Y015

@_typing.final
class SeedFile(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PATH_FIELD_NUMBER: _builtins.int
    CONTENT_FIELD_NUMBER: _builtins.int
    MODE_FIELD_NUMBER: _builtins.int
    path: _builtins.str
    """Absolute and clean, strictly inside a key path."""
    content: _builtins.bytes
    mode: _builtins.int
    """Permission bits; zero means 0644."""
    def __init__(
        self,
        *,
        path: _builtins.str = ...,
        content: _builtins.bytes = ...,
        mode: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["content", b"content", "mode", b"mode", "path", b"path"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SeedFile: _TypeAlias = SeedFile  # noqa: Y015

@_typing.final
class CreateSandboxResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUNTIME_FIELD_NUMBER: _builtins.int
    runtime: _builtins.str
    """Container runtime the sandbox got, `runc` or `runsc`. Recorded as the run's isolation level."""
    def __init__(
        self,
        *,
        runtime: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["runtime", b"runtime"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CreateSandboxResponse: _TypeAlias = CreateSandboxResponse  # noqa: Y015

@_typing.final
class ExecRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    SANDBOX_ID_FIELD_NUMBER: _builtins.int
    CALL_ID_FIELD_NUMBER: _builtins.int
    ARGV_FIELD_NUMBER: _builtins.int
    CWD_FIELD_NUMBER: _builtins.int
    USER_FIELD_NUMBER: _builtins.int
    TIMEOUT_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    sandbox_id: _builtins.str
    call_id: _builtins.str
    """The tool call this command belongs to. Changes and processes are attributed to it."""
    cwd: _builtins.str
    user: _builtins.str
    """Empty runs as the image's user."""
    @_builtins.property
    def argv(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def timeout(self) -> _duration_pb2.Duration:
        """Required. On expiry the command and its descendants are killed."""

    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
        sandbox_id: _builtins.str = ...,
        call_id: _builtins.str = ...,
        argv: _abc.Iterable[_builtins.str] | None = ...,
        cwd: _builtins.str = ...,
        user: _builtins.str = ...,
        timeout: _duration_pb2.Duration | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["timeout", b"timeout"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["argv", b"argv", "call_id", b"call_id", "cwd", b"cwd", "run_id", b"run_id", "sandbox_id", b"sandbox_id", "timeout", b"timeout", "user", b"user"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ExecRequest: _TypeAlias = ExecRequest  # noqa: Y015

@_typing.final
class ExecResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    HEADER_FIELD_NUMBER: _builtins.int
    BLOB_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def header(self) -> Global___ExecHeader: ...
    @_builtins.property
    def blob(self) -> Global___BlobChunk: ...
    def __init__(
        self,
        *,
        header: Global___ExecHeader | None = ...,
        blob: Global___BlobChunk | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["blob", b"blob", "header", b"header", "item", b"item"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["blob", b"blob", "header", b"header", "item", b"item"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_item: _TypeAlias = _typing.Literal["header", "blob"]  # noqa: Y015
    _WhichOneofArgType_item: _TypeAlias = _typing.Literal["item", b"item"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_item) -> _WhichOneofReturnType_item | None: ...

Global___ExecResponse: _TypeAlias = ExecResponse  # noqa: Y015

@_typing.final
class ExecHeader(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    EXIT_CODE_FIELD_NUMBER: _builtins.int
    TIMED_OUT_FIELD_NUMBER: _builtins.int
    DURATION_FIELD_NUMBER: _builtins.int
    STDOUT_FIELD_NUMBER: _builtins.int
    STDERR_FIELD_NUMBER: _builtins.int
    BACKGROUND_CHANGES_FIELD_NUMBER: _builtins.int
    CHANGES_FIELD_NUMBER: _builtins.int
    PROCESSES_FIELD_NUMBER: _builtins.int
    exit_code: _builtins.int
    """-1 when timed out."""
    timed_out: _builtins.bool
    @_builtins.property
    def duration(self) -> _duration_pb2.Duration: ...
    @_builtins.property
    def stdout(self) -> Global___Output: ...
    @_builtins.property
    def stderr(self) -> Global___Output: ...
    @_builtins.property
    def background_changes(self) -> _containers.RepeatedCompositeFieldContainer[Global___FsChange]:
        """Changed between the previous call on this sandbox and this one: written by background
        processes. Always `AMBIGUOUS`.
        """

    @_builtins.property
    def changes(self) -> _containers.RepeatedCompositeFieldContainer[Global___FsChange]:
        """Changed while this call ran."""

    @_builtins.property
    def processes(self) -> _containers.RepeatedCompositeFieldContainer[Global___Process]:
        """Started while this call ran and still alive after it."""

    def __init__(
        self,
        *,
        exit_code: _builtins.int = ...,
        timed_out: _builtins.bool = ...,
        duration: _duration_pb2.Duration | None = ...,
        stdout: Global___Output | None = ...,
        stderr: Global___Output | None = ...,
        background_changes: _abc.Iterable[Global___FsChange] | None = ...,
        changes: _abc.Iterable[Global___FsChange] | None = ...,
        processes: _abc.Iterable[Global___Process] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["duration", b"duration", "stderr", b"stderr", "stdout", b"stdout"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["background_changes", b"background_changes", "changes", b"changes", "duration", b"duration", "exit_code", b"exit_code", "processes", b"processes", "stderr", b"stderr", "stdout", b"stdout", "timed_out", b"timed_out"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ExecHeader: _TypeAlias = ExecHeader  # noqa: Y015

@_typing.final
class Output(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    INLINE_FIELD_NUMBER: _builtins.int
    SIZE_FIELD_NUMBER: _builtins.int
    BLOB_SHA256_FIELD_NUMBER: _builtins.int
    CAPPED_FIELD_NUMBER: _builtins.int
    inline: _builtins.bytes
    """The first bytes, up to sandboxd's inline limit."""
    size: _builtins.int
    """Bytes the command produced in total."""
    blob_sha256: _builtins.str
    """Set when the output is longer than `inline`: the kept output follows as a blob with this
    hash.
    """
    capped: _builtins.bool
    """The output exceeded sandboxd's blob limit, and only the first limit bytes were kept."""
    def __init__(
        self,
        *,
        inline: _builtins.bytes = ...,
        size: _builtins.int = ...,
        blob_sha256: _builtins.str = ...,
        capped: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["blob_sha256", b"blob_sha256", "capped", b"capped", "inline", b"inline", "size", b"size"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Output: _TypeAlias = Output  # noqa: Y015

@_typing.final
class FsChange(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _Op:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _OpEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[FsChange._Op.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        OP_UNSPECIFIED: FsChange._Op.ValueType  # 0
        OP_CREATE: FsChange._Op.ValueType  # 1
        OP_MODIFY: FsChange._Op.ValueType  # 2
        OP_DELETE: FsChange._Op.ValueType  # 3

    class Op(_Op, metaclass=_OpEnumTypeWrapper): ...
    OP_UNSPECIFIED: FsChange.Op.ValueType  # 0
    OP_CREATE: FsChange.Op.ValueType  # 1
    OP_MODIFY: FsChange.Op.ValueType  # 2
    OP_DELETE: FsChange.Op.ValueType  # 3

    class _Kind:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _KindEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[FsChange._Kind.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        KIND_UNSPECIFIED: FsChange._Kind.ValueType  # 0
        KIND_FILE: FsChange._Kind.ValueType  # 1
        KIND_DIR: FsChange._Kind.ValueType  # 2
        KIND_SYMLINK: FsChange._Kind.ValueType  # 3
        KIND_OTHER: FsChange._Kind.ValueType  # 4
        """A fifo, socket, or device. Never opened, so it has no hash."""

    class Kind(_Kind, metaclass=_KindEnumTypeWrapper): ...
    KIND_UNSPECIFIED: FsChange.Kind.ValueType  # 0
    KIND_FILE: FsChange.Kind.ValueType  # 1
    KIND_DIR: FsChange.Kind.ValueType  # 2
    KIND_SYMLINK: FsChange.Kind.ValueType  # 3
    KIND_OTHER: FsChange.Kind.ValueType  # 4
    """A fifo, socket, or device. Never opened, so it has no hash."""

    class _Attribution:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _AttributionEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[FsChange._Attribution.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        ATTRIBUTION_UNSPECIFIED: FsChange._Attribution.ValueType  # 0
        ATTRIBUTION_CALL: FsChange._Attribution.ValueType  # 1
        """Written by the call itself."""
        ATTRIBUTION_AMBIGUOUS: FsChange._Attribution.ValueType  # 2
        """A background process may have written it; see `candidate_calls`."""

    class Attribution(_Attribution, metaclass=_AttributionEnumTypeWrapper): ...
    ATTRIBUTION_UNSPECIFIED: FsChange.Attribution.ValueType  # 0
    ATTRIBUTION_CALL: FsChange.Attribution.ValueType  # 1
    """Written by the call itself."""
    ATTRIBUTION_AMBIGUOUS: FsChange.Attribution.ValueType  # 2
    """A background process may have written it; see `candidate_calls`."""

    PATH_FIELD_NUMBER: _builtins.int
    OP_FIELD_NUMBER: _builtins.int
    KIND_FIELD_NUMBER: _builtins.int
    UID_FIELD_NUMBER: _builtins.int
    MODE_FIELD_NUMBER: _builtins.int
    SIZE_FIELD_NUMBER: _builtins.int
    BEFORE_SHA256_FIELD_NUMBER: _builtins.int
    AFTER_SHA256_FIELD_NUMBER: _builtins.int
    PROTECTED_FIELD_NUMBER: _builtins.int
    ATTRIBUTION_FIELD_NUMBER: _builtins.int
    CANDIDATE_CALLS_FIELD_NUMBER: _builtins.int
    CONTENT_FIELD_NUMBER: _builtins.int
    path: _builtins.str
    """Path inside the sandbox."""
    op: Global___FsChange.Op.ValueType
    kind: Global___FsChange.Kind.ValueType
    uid: _builtins.int
    """Owner after the change; before it for a delete."""
    mode: _builtins.int
    size: _builtins.int
    before_sha256: _builtins.str
    """Hash of a file's content or a symlink's target. Empty for directories and for the side
    that does not exist.
    """
    after_sha256: _builtins.str
    protected: _builtins.bool
    attribution: Global___FsChange.Attribution.ValueType
    content: _builtins.bool
    """The new content follows as a blob with hash `after_sha256`. Unset for files over the
    content limit.
    """
    @_builtins.property
    def candidate_calls(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Calls whose processes were alive in the window. Empty when unknown."""

    def __init__(
        self,
        *,
        path: _builtins.str = ...,
        op: Global___FsChange.Op.ValueType = ...,
        kind: Global___FsChange.Kind.ValueType = ...,
        uid: _builtins.int = ...,
        mode: _builtins.int = ...,
        size: _builtins.int = ...,
        before_sha256: _builtins.str = ...,
        after_sha256: _builtins.str = ...,
        protected: _builtins.bool = ...,
        attribution: Global___FsChange.Attribution.ValueType = ...,
        candidate_calls: _abc.Iterable[_builtins.str] | None = ...,
        content: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["after_sha256", b"after_sha256", "attribution", b"attribution", "before_sha256", b"before_sha256", "candidate_calls", b"candidate_calls", "content", b"content", "kind", b"kind", "mode", b"mode", "op", b"op", "path", b"path", "protected", b"protected", "size", b"size", "uid", b"uid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___FsChange: _TypeAlias = FsChange  # noqa: Y015

@_typing.final
class Process(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PID_FIELD_NUMBER: _builtins.int
    PPID_FIELD_NUMBER: _builtins.int
    USER_FIELD_NUMBER: _builtins.int
    CMDLINE_FIELD_NUMBER: _builtins.int
    pid: _builtins.int
    """Process id inside the sandbox, read from the sandbox's own /proc."""
    ppid: _builtins.int
    user: _builtins.str
    """Name from the sandbox's /etc/passwd, or the uid when it has none."""
    cmdline: _builtins.str
    def __init__(
        self,
        *,
        pid: _builtins.int = ...,
        ppid: _builtins.int = ...,
        user: _builtins.str = ...,
        cmdline: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["cmdline", b"cmdline", "pid", b"pid", "ppid", b"ppid", "user", b"user"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Process: _TypeAlias = Process  # noqa: Y015

@_typing.final
class BlobChunk(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SHA256_FIELD_NUMBER: _builtins.int
    DATA_FIELD_NUMBER: _builtins.int
    LAST_FIELD_NUMBER: _builtins.int
    sha256: _builtins.str
    data: _builtins.bytes
    last: _builtins.bool
    def __init__(
        self,
        *,
        sha256: _builtins.str = ...,
        data: _builtins.bytes = ...,
        last: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["data", b"data", "last", b"last", "sha256", b"sha256"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___BlobChunk: _TypeAlias = BlobChunk  # noqa: Y015

@_typing.final
class ReadFileRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    SANDBOX_ID_FIELD_NUMBER: _builtins.int
    PATH_FIELD_NUMBER: _builtins.int
    MAX_BYTES_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    sandbox_id: _builtins.str
    path: _builtins.str
    max_bytes: _builtins.int
    """Zero means sandboxd's content limit."""
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
        sandbox_id: _builtins.str = ...,
        path: _builtins.str = ...,
        max_bytes: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["max_bytes", b"max_bytes", "path", b"path", "run_id", b"run_id", "sandbox_id", b"sandbox_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReadFileRequest: _TypeAlias = ReadFileRequest  # noqa: Y015

@_typing.final
class ReadFileResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CONTENT_FIELD_NUMBER: _builtins.int
    SIZE_FIELD_NUMBER: _builtins.int
    TRUNCATED_FIELD_NUMBER: _builtins.int
    content: _builtins.bytes
    size: _builtins.int
    truncated: _builtins.bool
    def __init__(
        self,
        *,
        content: _builtins.bytes = ...,
        size: _builtins.int = ...,
        truncated: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["content", b"content", "size", b"size", "truncated", b"truncated"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReadFileResponse: _TypeAlias = ReadFileResponse  # noqa: Y015

@_typing.final
class FinalDiffRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["run_id", b"run_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___FinalDiffRequest: _TypeAlias = FinalDiffRequest  # noqa: Y015

@_typing.final
class FinalDiffResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CHANGES_FIELD_NUMBER: _builtins.int
    BLOB_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def changes(self) -> Global___SandboxChanges: ...
    @_builtins.property
    def blob(self) -> Global___BlobChunk: ...
    def __init__(
        self,
        *,
        changes: Global___SandboxChanges | None = ...,
        blob: Global___BlobChunk | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["blob", b"blob", "changes", b"changes", "item", b"item"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["blob", b"blob", "changes", b"changes", "item", b"item"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_item: _TypeAlias = _typing.Literal["changes", "blob"]  # noqa: Y015
    _WhichOneofArgType_item: _TypeAlias = _typing.Literal["item", b"item"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_item) -> _WhichOneofReturnType_item | None: ...

Global___FinalDiffResponse: _TypeAlias = FinalDiffResponse  # noqa: Y015

@_typing.final
class SandboxChanges(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SANDBOX_ID_FIELD_NUMBER: _builtins.int
    CHANGES_FIELD_NUMBER: _builtins.int
    sandbox_id: _builtins.str
    @_builtins.property
    def changes(self) -> _containers.RepeatedCompositeFieldContainer[Global___FsChange]: ...
    def __init__(
        self,
        *,
        sandbox_id: _builtins.str = ...,
        changes: _abc.Iterable[Global___FsChange] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["changes", b"changes", "sandbox_id", b"sandbox_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SandboxChanges: _TypeAlias = SandboxChanges  # noqa: Y015

@_typing.final
class DestroyRunRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["run_id", b"run_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DestroyRunRequest: _TypeAlias = DestroyRunRequest  # noqa: Y015

@_typing.final
class DestroyRunResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DestroyRunResponse: _TypeAlias = DestroyRunResponse  # noqa: Y015
