"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
from swarmeval.proto.swarmeval.sandbox.v1 import sandbox_pb2 as _sandbox_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class SandboxServiceStub:
    """SandboxService is sandboxd's API. Its only caller is the worker that owns the run.
    Behavior: docs/services/sandboxd.md.

    Identifiers: `run_id` matches [A-Za-z0-9][A-Za-z0-9._-]{0,127}; `sandbox_id` matches
    [a-z][a-z0-9_]{0,62} (the case format's names). Anything else is INVALID_ARGUMENT.
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> SandboxServiceAsyncStub: ...
    CreateRun: _grpc.UnaryUnaryMultiCallable[_sandbox_pb2.CreateRunRequest, _sandbox_pb2.CreateRunResponse]
    """Creates a run's networks: one per sandbox, on which the host has no address. Must come
    before the run's CreateSandbox calls. Fails with ALREADY_EXISTS if the run exists.
    """
    CreateSandbox: _grpc.UnaryUnaryMultiCallable[_sandbox_pb2.CreateSandboxRequest, _sandbox_pb2.CreateSandboxResponse]
    """Creates and starts one sandbox on its network, made by CreateRun. Each top-level key path starts as a copy of the image's
    content at that path, plus any seed files. Fails with ALREADY_EXISTS if the sandbox exists.
    """
    Exec: _grpc.UnaryStreamMultiCallable[_sandbox_pb2.ExecRequest, _sandbox_pb2.ExecResponse]
    """Runs one tool call. The stream carries exactly one header first, then the blobs the
    header refers to, each as one or more chunks. Calls on one sandbox run one at a time.
    """
    ReadFile: _grpc.UnaryUnaryMultiCallable[_sandbox_pb2.ReadFileRequest, _sandbox_pb2.ReadFileResponse]
    """Reads one file from a sandbox without running anything inside it. For final-state scorers."""
    FinalDiff: _grpc.UnaryStreamMultiCallable[_sandbox_pb2.FinalDiffRequest, _sandbox_pb2.FinalDiffResponse]
    """Diffs every sandbox of a run against its last manifest, catching writes by background
    processes after the last call. Every change is attributed `AMBIGUOUS`.
    """
    DestroyRun: _grpc.UnaryUnaryMultiCallable[_sandbox_pb2.DestroyRunRequest, _sandbox_pb2.DestroyRunResponse]
    """Removes every container and network labeled with the run, and the run's state directory."""

@_typing.type_check_only
class SandboxServiceAsyncStub(SandboxServiceStub):
    """SandboxService is sandboxd's API. Its only caller is the worker that owns the run.
    Behavior: docs/services/sandboxd.md.

    Identifiers: `run_id` matches [A-Za-z0-9][A-Za-z0-9._-]{0,127}; `sandbox_id` matches
    [a-z][a-z0-9_]{0,62} (the case format's names). Anything else is INVALID_ARGUMENT.
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    CreateRun: _aio.UnaryUnaryMultiCallable[_sandbox_pb2.CreateRunRequest, _sandbox_pb2.CreateRunResponse]  # type: ignore[assignment]
    """Creates a run's networks: one per sandbox, on which the host has no address. Must come
    before the run's CreateSandbox calls. Fails with ALREADY_EXISTS if the run exists.
    """
    CreateSandbox: _aio.UnaryUnaryMultiCallable[_sandbox_pb2.CreateSandboxRequest, _sandbox_pb2.CreateSandboxResponse]  # type: ignore[assignment]
    """Creates and starts one sandbox on its network, made by CreateRun. Each top-level key path starts as a copy of the image's
    content at that path, plus any seed files. Fails with ALREADY_EXISTS if the sandbox exists.
    """
    Exec: _aio.UnaryStreamMultiCallable[_sandbox_pb2.ExecRequest, _sandbox_pb2.ExecResponse]  # type: ignore[assignment]
    """Runs one tool call. The stream carries exactly one header first, then the blobs the
    header refers to, each as one or more chunks. Calls on one sandbox run one at a time.
    """
    ReadFile: _aio.UnaryUnaryMultiCallable[_sandbox_pb2.ReadFileRequest, _sandbox_pb2.ReadFileResponse]  # type: ignore[assignment]
    """Reads one file from a sandbox without running anything inside it. For final-state scorers."""
    FinalDiff: _aio.UnaryStreamMultiCallable[_sandbox_pb2.FinalDiffRequest, _sandbox_pb2.FinalDiffResponse]  # type: ignore[assignment]
    """Diffs every sandbox of a run against its last manifest, catching writes by background
    processes after the last call. Every change is attributed `AMBIGUOUS`.
    """
    DestroyRun: _aio.UnaryUnaryMultiCallable[_sandbox_pb2.DestroyRunRequest, _sandbox_pb2.DestroyRunResponse]  # type: ignore[assignment]
    """Removes every container and network labeled with the run, and the run's state directory."""

class SandboxServiceServicer(metaclass=_abc_1.ABCMeta):
    """SandboxService is sandboxd's API. Its only caller is the worker that owns the run.
    Behavior: docs/services/sandboxd.md.

    Identifiers: `run_id` matches [A-Za-z0-9][A-Za-z0-9._-]{0,127}; `sandbox_id` matches
    [a-z][a-z0-9_]{0,62} (the case format's names). Anything else is INVALID_ARGUMENT.
    """

    @_abc_1.abstractmethod
    def CreateRun(
        self,
        request: _sandbox_pb2.CreateRunRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_sandbox_pb2.CreateRunResponse, _abc.Awaitable[_sandbox_pb2.CreateRunResponse]]:
        """Creates a run's networks: one per sandbox, on which the host has no address. Must come
        before the run's CreateSandbox calls. Fails with ALREADY_EXISTS if the run exists.
        """

    @_abc_1.abstractmethod
    def CreateSandbox(
        self,
        request: _sandbox_pb2.CreateSandboxRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_sandbox_pb2.CreateSandboxResponse, _abc.Awaitable[_sandbox_pb2.CreateSandboxResponse]]:
        """Creates and starts one sandbox on its network, made by CreateRun. Each top-level key path starts as a copy of the image's
        content at that path, plus any seed files. Fails with ALREADY_EXISTS if the sandbox exists.
        """

    @_abc_1.abstractmethod
    def Exec(
        self,
        request: _sandbox_pb2.ExecRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_sandbox_pb2.ExecResponse], _abc.AsyncIterator[_sandbox_pb2.ExecResponse]]:
        """Runs one tool call. The stream carries exactly one header first, then the blobs the
        header refers to, each as one or more chunks. Calls on one sandbox run one at a time.
        """

    @_abc_1.abstractmethod
    def ReadFile(
        self,
        request: _sandbox_pb2.ReadFileRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_sandbox_pb2.ReadFileResponse, _abc.Awaitable[_sandbox_pb2.ReadFileResponse]]:
        """Reads one file from a sandbox without running anything inside it. For final-state scorers."""

    @_abc_1.abstractmethod
    def FinalDiff(
        self,
        request: _sandbox_pb2.FinalDiffRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_sandbox_pb2.FinalDiffResponse], _abc.AsyncIterator[_sandbox_pb2.FinalDiffResponse]]:
        """Diffs every sandbox of a run against its last manifest, catching writes by background
        processes after the last call. Every change is attributed `AMBIGUOUS`.
        """

    @_abc_1.abstractmethod
    def DestroyRun(
        self,
        request: _sandbox_pb2.DestroyRunRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_sandbox_pb2.DestroyRunResponse, _abc.Awaitable[_sandbox_pb2.DestroyRunResponse]]:
        """Removes every container and network labeled with the run, and the run's state directory."""

def add_SandboxServiceServicer_to_server(servicer: SandboxServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
