# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from swarmeval.proto.swarmeval.modelgw.v1 import recorder_pb2 as swarmeval_dot_proto_dot_swarmeval_dot_modelgw_dot_v1_dot_recorder__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in swarmeval/proto/swarmeval/modelgw/v1/recorder_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RecorderServiceStub:
    """RecorderService carries model-gateway's record of every model call back to the worker that owns the
    run, so the worker commits it before the caller gets the response.
    Behavior: docs/services/model-gateway.md.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Attach = channel.stream_stream(
                '/swarmeval.modelgw.v1.RecorderService/Attach',
                request_serializer=swarmeval_dot_proto_dot_swarmeval_dot_modelgw_dot_v1_dot_recorder__pb2.AttachRequest.SerializeToString,
                response_deserializer=swarmeval_dot_proto_dot_swarmeval_dot_modelgw_dot_v1_dot_recorder__pb2.AttachResponse.FromString,
                _registered_method=True)


class RecorderServiceServicer:
    """RecorderService carries model-gateway's record of every model call back to the worker that owns the
    run, so the worker commits it before the caller gets the response.
    Behavior: docs/services/model-gateway.md.
    """

    def Attach(self, request_iterator, context):
        """One stream per run, dialed by the run's worker. The worker's first message is a `Hello`;
        the gateway answers `Attached` once the run's keys accept calls. After that the gateway
        sends one `CallRecord` per completed call and holds the HTTP response until the worker
        answers with an `Ack` or `Reject` for it. A stream for the same run with a higher
        `owner_epoch` replaces this one; a lower or equal one is refused with FAILED_PRECONDITION.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecorderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Attach': grpc.stream_stream_rpc_method_handler(
                    servicer.Attach,
                    request_deserializer=swarmeval_dot_proto_dot_swarmeval_dot_modelgw_dot_v1_dot_recorder__pb2.AttachRequest.FromString,
                    response_serializer=swarmeval_dot_proto_dot_swarmeval_dot_modelgw_dot_v1_dot_recorder__pb2.AttachResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swarmeval.modelgw.v1.RecorderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('swarmeval.modelgw.v1.RecorderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RecorderService:
    """RecorderService carries model-gateway's record of every model call back to the worker that owns the
    run, so the worker commits it before the caller gets the response.
    Behavior: docs/services/model-gateway.md.
    """

    @staticmethod
    def Attach(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/swarmeval.modelgw.v1.RecorderService/Attach',
            swarmeval_dot_proto_dot_swarmeval_dot_modelgw_dot_v1_dot_recorder__pb2.AttachRequest.SerializeToString,
            swarmeval_dot_proto_dot_swarmeval_dot_modelgw_dot_v1_dot_recorder__pb2.AttachResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
