"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class AttachRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    HELLO_FIELD_NUMBER: _builtins.int
    ACK_FIELD_NUMBER: _builtins.int
    REJECT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def hello(self) -> Global___Hello: ...
    @_builtins.property
    def ack(self) -> Global___Ack: ...
    @_builtins.property
    def reject(self) -> Global___Reject: ...
    def __init__(
        self,
        *,
        hello: Global___Hello | None = ...,
        ack: Global___Ack | None = ...,
        reject: Global___Reject | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["ack", b"ack", "hello", b"hello", "item", b"item", "reject", b"reject"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ack", b"ack", "hello", b"hello", "item", b"item", "reject", b"reject"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_item: _TypeAlias = _typing.Literal["hello", "ack", "reject"]  # noqa: Y015
    _WhichOneofArgType_item: _TypeAlias = _typing.Literal["item", b"item"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_item) -> _WhichOneofReturnType_item | None: ...

Global___AttachRequest: _TypeAlias = AttachRequest  # noqa: Y015

@_typing.final
class AttachResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ATTACHED_FIELD_NUMBER: _builtins.int
    RECORD_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def attached(self) -> Global___Attached: ...
    @_builtins.property
    def record(self) -> Global___CallRecord: ...
    def __init__(
        self,
        *,
        attached: Global___Attached | None = ...,
        record: Global___CallRecord | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["attached", b"attached", "item", b"item", "record", b"record"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["attached", b"attached", "item", b"item", "record", b"record"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_item: _TypeAlias = _typing.Literal["attached", "record"]  # noqa: Y015
    _WhichOneofArgType_item: _TypeAlias = _typing.Literal["item", b"item"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_item) -> _WhichOneofReturnType_item | None: ...

Global___AttachResponse: _TypeAlias = AttachResponse  # noqa: Y015

@_typing.final
class Hello(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    OWNER_EPOCH_FIELD_NUMBER: _builtins.int
    KEYS_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    owner_epoch: _builtins.int
    @_builtins.property
    def keys(self) -> _containers.RepeatedCompositeFieldContainer[Global___CallerKey]: ...
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
        owner_epoch: _builtins.int = ...,
        keys: _abc.Iterable[Global___CallerKey] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["keys", b"keys", "owner_epoch", b"owner_epoch", "run_id", b"run_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Hello: _TypeAlias = Hello  # noqa: Y015

@_typing.final
class CallerKey(_message.Message):
    """A virtual key and who calls with it. Valid only while this stream is attached."""

    DESCRIPTOR: _descriptor.Descriptor

    KEY_FIELD_NUMBER: _builtins.int
    CALLER_FIELD_NUMBER: _builtins.int
    key: _builtins.str
    caller: _builtins.str
    """`agent:<agent_id>` or `extension:<instance_id>`."""
    def __init__(
        self,
        *,
        key: _builtins.str = ...,
        caller: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["caller", b"caller", "key", b"key"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CallerKey: _TypeAlias = CallerKey  # noqa: Y015

@_typing.final
class Attached(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Attached: _TypeAlias = Attached  # noqa: Y015

@_typing.final
class CallRecord(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CALL_ID_FIELD_NUMBER: _builtins.int
    CALLER_FIELD_NUMBER: _builtins.int
    REQUEST_SHA256_FIELD_NUMBER: _builtins.int
    RESPONSE_JSON_FIELD_NUMBER: _builtins.int
    UPSTREAM_RESPONSE_JSON_FIELD_NUMBER: _builtins.int
    UPSTREAM_FIELD_NUMBER: _builtins.int
    LATENCY_SECONDS_FIELD_NUMBER: _builtins.int
    ATTEMPTS_FIELD_NUMBER: _builtins.int
    call_id: _builtins.str
    """The worker's id for the call, from the request's `X-SwarmEval-Call-Id` header."""
    caller: _builtins.str
    request_sha256: _builtins.str
    """sha256 of the HTTP request body exactly as the gateway received it."""
    response_json: _builtins.str
    """The response the caller will get: an OpenAI Chat Completions response, as JSON."""
    upstream_response_json: _builtins.str
    """The backend's response body, as JSON, before the gateway normalized it."""
    latency_seconds: _builtins.float
    attempts: _builtins.int
    """HTTP attempts the call took, retries included."""
    @_builtins.property
    def upstream(self) -> Global___Upstream: ...
    def __init__(
        self,
        *,
        call_id: _builtins.str = ...,
        caller: _builtins.str = ...,
        request_sha256: _builtins.str = ...,
        response_json: _builtins.str = ...,
        upstream_response_json: _builtins.str = ...,
        upstream: Global___Upstream | None = ...,
        latency_seconds: _builtins.float = ...,
        attempts: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["upstream", b"upstream"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["attempts", b"attempts", "call_id", b"call_id", "caller", b"caller", "latency_seconds", b"latency_seconds", "request_sha256", b"request_sha256", "response_json", b"response_json", "upstream", b"upstream", "upstream_response_json", b"upstream_response_json"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CallRecord: _TypeAlias = CallRecord  # noqa: Y015

@_typing.final
class Upstream(_message.Message):
    """What the gateway sent to, and learned from, the backend."""

    DESCRIPTOR: _descriptor.Descriptor

    BACKEND_FIELD_NUMBER: _builtins.int
    MODEL_FIELD_NUMBER: _builtins.int
    SERVED_MODEL_FIELD_NUMBER: _builtins.int
    REASONING_PASSBACK_FIELD_NUMBER: _builtins.int
    WEIGHTS_HASH_FIELD_NUMBER: _builtins.int
    SYSTEM_FINGERPRINT_FIELD_NUMBER: _builtins.int
    SAMPLING_JSON_FIELD_NUMBER: _builtins.int
    REASONING_VISIBILITY_FIELD_NUMBER: _builtins.int
    backend: _builtins.str
    """Deployment name of the backend."""
    model: _builtins.str
    """Model name the backend was asked for."""
    served_model: _builtins.str
    """Model name or version the backend reported."""
    reasoning_passback: _builtins.str
    """`none`, `within_turn`, or `all`."""
    weights_hash: _builtins.str
    """Set for self-hosted backends."""
    system_fingerprint: _builtins.str
    sampling_json: _builtins.str
    """Sampling parameters actually sent, request values and backend defaults merged, as a JSON
    object.
    """
    reasoning_visibility: _builtins.str
    """`full` while only open-weight models are supported."""
    def __init__(
        self,
        *,
        backend: _builtins.str = ...,
        model: _builtins.str = ...,
        served_model: _builtins.str = ...,
        reasoning_passback: _builtins.str = ...,
        weights_hash: _builtins.str = ...,
        system_fingerprint: _builtins.str = ...,
        sampling_json: _builtins.str = ...,
        reasoning_visibility: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["backend", b"backend", "model", b"model", "reasoning_passback", b"reasoning_passback", "reasoning_visibility", b"reasoning_visibility", "sampling_json", b"sampling_json", "served_model", b"served_model", "system_fingerprint", b"system_fingerprint", "weights_hash", b"weights_hash"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Upstream: _TypeAlias = Upstream  # noqa: Y015

@_typing.final
class Ack(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CALL_ID_FIELD_NUMBER: _builtins.int
    EVENT_ID_FIELD_NUMBER: _builtins.int
    call_id: _builtins.str
    event_id: _builtins.str
    """Id of the committed event that holds the record."""
    def __init__(
        self,
        *,
        call_id: _builtins.str = ...,
        event_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["call_id", b"call_id", "event_id", b"event_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Ack: _TypeAlias = Ack  # noqa: Y015

@_typing.final
class Reject(_message.Message):
    """The worker could not commit the record. The gateway fails the call with 503."""

    DESCRIPTOR: _descriptor.Descriptor

    CALL_ID_FIELD_NUMBER: _builtins.int
    REASON_FIELD_NUMBER: _builtins.int
    call_id: _builtins.str
    reason: _builtins.str
    def __init__(
        self,
        *,
        call_id: _builtins.str = ...,
        reason: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["call_id", b"call_id", "reason", b"reason"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Reject: _TypeAlias = Reject  # noqa: Y015
