"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
from swarmeval.proto.swarmeval.modelgw.v1 import recorder_pb2 as _recorder_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class RecorderServiceStub:
    """RecorderService carries model-gateway's record of every model call back to the worker that owns the
    run, so the worker commits it before the caller gets the response.
    Behavior: docs/services/model-gateway.md.
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> RecorderServiceAsyncStub: ...
    Attach: _grpc.StreamStreamMultiCallable[_recorder_pb2.AttachRequest, _recorder_pb2.AttachResponse]
    """One stream per run, dialed by the run's worker. The worker's first message is a `Hello`;
    the gateway answers `Attached` once the run's keys accept calls. After that the gateway
    sends one `CallRecord` per completed call and holds the HTTP response until the worker
    answers with an `Ack` or `Reject` for it. A stream for the same run with a higher
    `owner_epoch` replaces this one; a lower or equal one is refused with FAILED_PRECONDITION.
    """

@_typing.type_check_only
class RecorderServiceAsyncStub(RecorderServiceStub):
    """RecorderService carries model-gateway's record of every model call back to the worker that owns the
    run, so the worker commits it before the caller gets the response.
    Behavior: docs/services/model-gateway.md.
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    Attach: _aio.StreamStreamMultiCallable[_recorder_pb2.AttachRequest, _recorder_pb2.AttachResponse]  # type: ignore[assignment]
    """One stream per run, dialed by the run's worker. The worker's first message is a `Hello`;
    the gateway answers `Attached` once the run's keys accept calls. After that the gateway
    sends one `CallRecord` per completed call and holds the HTTP response until the worker
    answers with an `Ack` or `Reject` for it. A stream for the same run with a higher
    `owner_epoch` replaces this one; a lower or equal one is refused with FAILED_PRECONDITION.
    """

class RecorderServiceServicer(metaclass=_abc_1.ABCMeta):
    """RecorderService carries model-gateway's record of every model call back to the worker that owns the
    run, so the worker commits it before the caller gets the response.
    Behavior: docs/services/model-gateway.md.
    """

    @_abc_1.abstractmethod
    def Attach(
        self,
        request_iterator: _MaybeAsyncIterator[_recorder_pb2.AttachRequest],
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_recorder_pb2.AttachResponse], _abc.AsyncIterator[_recorder_pb2.AttachResponse]]:
        """One stream per run, dialed by the run's worker. The worker's first message is a `Hello`;
        the gateway answers `Attached` once the run's keys accept calls. After that the gateway
        sends one `CallRecord` per completed call and holds the HTTP response until the worker
        answers with an `Ack` or `Reject` for it. A stream for the same run with a higher
        `owner_epoch` replaces this one; a lower or equal one is refused with FAILED_PRECONDITION.
        """

def add_RecorderServiceServicer_to_server(servicer: RecorderServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
