"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class AttachRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    HELLO_FIELD_NUMBER: _builtins.int
    ACK_FIELD_NUMBER: _builtins.int
    REJECT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def hello(self) -> Global___Hello: ...
    @_builtins.property
    def ack(self) -> Global___Ack: ...
    @_builtins.property
    def reject(self) -> Global___Reject: ...
    def __init__(
        self,
        *,
        hello: Global___Hello | None = ...,
        ack: Global___Ack | None = ...,
        reject: Global___Reject | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["ack", b"ack", "hello", b"hello", "item", b"item", "reject", b"reject"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ack", b"ack", "hello", b"hello", "item", b"item", "reject", b"reject"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_item: _TypeAlias = _typing.Literal["hello", "ack", "reject"]  # noqa: Y015
    _WhichOneofArgType_item: _TypeAlias = _typing.Literal["item", b"item"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_item) -> _WhichOneofReturnType_item | None: ...

Global___AttachRequest: _TypeAlias = AttachRequest  # noqa: Y015

@_typing.final
class AttachResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ATTACHED_FIELD_NUMBER: _builtins.int
    RECORD_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def attached(self) -> Global___Attached: ...
    @_builtins.property
    def record(self) -> Global___Record: ...
    def __init__(
        self,
        *,
        attached: Global___Attached | None = ...,
        record: Global___Record | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["attached", b"attached", "item", b"item", "record", b"record"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["attached", b"attached", "item", b"item", "record", b"record"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_item: _TypeAlias = _typing.Literal["attached", "record"]  # noqa: Y015
    _WhichOneofArgType_item: _TypeAlias = _typing.Literal["item", b"item"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_item) -> _WhichOneofReturnType_item | None: ...

Global___AttachResponse: _TypeAlias = AttachResponse  # noqa: Y015

@_typing.final
class Hello(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    OWNER_EPOCH_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    owner_epoch: _builtins.int
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
        owner_epoch: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["owner_epoch", b"owner_epoch", "run_id", b"run_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Hello: _TypeAlias = Hello  # noqa: Y015

@_typing.final
class Attached(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Attached: _TypeAlias = Attached  # noqa: Y015

@_typing.final
class Record(_message.Message):
    """Record is one net.* event, held until the worker acks it. The worker maps it to an
    InfoEvent with source `swarmeval.<type>` (runtime spec decision 10).
    """

    DESCRIPTOR: _descriptor.Descriptor

    RECORD_ID_FIELD_NUMBER: _builtins.int
    SANDBOX_ID_FIELD_NUMBER: _builtins.int
    DST_IP_FIELD_NUMBER: _builtins.int
    DST_PORT_FIELD_NUMBER: _builtins.int
    DECISION_FIELD_NUMBER: _builtins.int
    MATCHED_RULE_FIELD_NUMBER: _builtins.int
    CONNECT_FIELD_NUMBER: _builtins.int
    UDP_FIELD_NUMBER: _builtins.int
    DNS_FIELD_NUMBER: _builtins.int
    record_id: _builtins.str
    """The gateway's id for this record, unique within the stream. The worker's Ack or Reject
    carries it back.
    """
    sandbox_id: _builtins.str
    """Which sandbox sent the traffic, from its source subnet."""
    dst_ip: _builtins.str
    """Original destination, kept by TPROXY."""
    dst_port: _builtins.int
    decision: _builtins.str
    """`allow`, `deny`, or `log_and_deny`."""
    matched_rule: _builtins.str
    """Identifier of the rule that decided, or empty for the default action."""
    @_builtins.property
    def connect(self) -> Global___Connect: ...
    @_builtins.property
    def udp(self) -> Global___Udp: ...
    @_builtins.property
    def dns(self) -> Global___Dns: ...
    def __init__(
        self,
        *,
        record_id: _builtins.str = ...,
        sandbox_id: _builtins.str = ...,
        dst_ip: _builtins.str = ...,
        dst_port: _builtins.int = ...,
        decision: _builtins.str = ...,
        matched_rule: _builtins.str = ...,
        connect: Global___Connect | None = ...,
        udp: Global___Udp | None = ...,
        dns: Global___Dns | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["connect", b"connect", "detail", b"detail", "dns", b"dns", "udp", b"udp"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["connect", b"connect", "decision", b"decision", "detail", b"detail", "dns", b"dns", "dst_ip", b"dst_ip", "dst_port", b"dst_port", "matched_rule", b"matched_rule", "record_id", b"record_id", "sandbox_id", b"sandbox_id", "udp", b"udp"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_detail: _TypeAlias = _typing.Literal["connect", "udp", "dns"]  # noqa: Y015
    _WhichOneofArgType_detail: _TypeAlias = _typing.Literal["detail", b"detail"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_detail) -> _WhichOneofReturnType_detail | None: ...

Global___Record: _TypeAlias = Record  # noqa: Y015

@_typing.final
class Connect(_message.Message):
    """Connect is one TCP connection. type `net.connect`."""

    DESCRIPTOR: _descriptor.Descriptor

    CLASSIFICATION_FIELD_NUMBER: _builtins.int
    SNI_FIELD_NUMBER: _builtins.int
    HTTP_HOST_FIELD_NUMBER: _builtins.int
    HTTP_METHOD_FIELD_NUMBER: _builtins.int
    HTTP_PATH_FIELD_NUMBER: _builtins.int
    classification: _builtins.str
    """What the first bytes looked like: `tls`, `http`, or `raw`."""
    sni: _builtins.str
    """Server name from a TLS ClientHello, when classification is `tls`."""
    http_host: _builtins.str
    """The first request's host, method, and path, when classification is `http`."""
    http_method: _builtins.str
    http_path: _builtins.str
    def __init__(
        self,
        *,
        classification: _builtins.str = ...,
        sni: _builtins.str = ...,
        http_host: _builtins.str = ...,
        http_method: _builtins.str = ...,
        http_path: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["classification", b"classification", "http_host", b"http_host", "http_method", b"http_method", "http_path", b"http_path", "sni", b"sni"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Connect: _TypeAlias = Connect  # noqa: Y015

@_typing.final
class Udp(_message.Message):
    """Udp is one UDP datagram flow to a non-DNS destination. type `net.udp`."""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Udp: _TypeAlias = Udp  # noqa: Y015

@_typing.final
class Dns(_message.Message):
    """Dns is one DNS query. type `net.dns`."""

    DESCRIPTOR: _descriptor.Descriptor

    QNAME_FIELD_NUMBER: _builtins.int
    QTYPE_FIELD_NUMBER: _builtins.int
    RCODE_FIELD_NUMBER: _builtins.int
    ANSWERS_FIELD_NUMBER: _builtins.int
    qname: _builtins.str
    qtype: _builtins.str
    """A, AAAA, TXT, and so on."""
    rcode: _builtins.str
    """The response code the gateway returned: NOERROR, NXDOMAIN, or REFUSED."""
    @_builtins.property
    def answers(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Addresses answered, if any."""

    def __init__(
        self,
        *,
        qname: _builtins.str = ...,
        qtype: _builtins.str = ...,
        rcode: _builtins.str = ...,
        answers: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["answers", b"answers", "qname", b"qname", "qtype", b"qtype", "rcode", b"rcode"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Dns: _TypeAlias = Dns  # noqa: Y015

@_typing.final
class Ack(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RECORD_ID_FIELD_NUMBER: _builtins.int
    EVENT_ID_FIELD_NUMBER: _builtins.int
    record_id: _builtins.str
    event_id: _builtins.str
    """Id of the committed event that holds the record, for the gateway's log. Optional."""
    def __init__(
        self,
        *,
        record_id: _builtins.str = ...,
        event_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["event_id", b"event_id", "record_id", b"record_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Ack: _TypeAlias = Ack  # noqa: Y015

@_typing.final
class Reject(_message.Message):
    """The worker could not commit the record. The gateway denies the traffic and closes it."""

    DESCRIPTOR: _descriptor.Descriptor

    RECORD_ID_FIELD_NUMBER: _builtins.int
    REASON_FIELD_NUMBER: _builtins.int
    record_id: _builtins.str
    reason: _builtins.str
    def __init__(
        self,
        *,
        record_id: _builtins.str = ...,
        reason: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["reason", b"reason", "record_id", b"record_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Reject: _TypeAlias = Reject  # noqa: Y015
