"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
from swarmeval.proto.swarmeval.netgw.v1 import netevents_pb2 as _netevents_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class NetEventsServiceStub:
    """NetEventsService carries net-gateway's record of every connection, datagram flow, and DNS
    query back to the worker that owns the run. The gateway holds the traffic until the worker
    commits the record and acks it, so a request that was let through is never unrecorded.
    Behavior: docs/services/net-gateway.md.

    Not served or called yet: net-gateway is deferred (2026-10-02). The contract is kept as
    designed so the work can resume from it.
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> NetEventsServiceAsyncStub: ...
    Attach: _grpc.StreamStreamMultiCallable[_netevents_pb2.AttachRequest, _netevents_pb2.AttachResponse]
    """One stream per run, dialed by the run's worker over mTLS with a per-run certificate. The
    worker's first message is a `Hello`; the gateway answers `Attached`. After that the gateway
    sends one `Record` per connection, datagram flow, or DNS query and holds that traffic until
    the worker answers with an `Ack` or `Reject` for it. A stream for the same run with a higher
    `owner_epoch` replaces this one; a lower or equal one is refused with FAILED_PRECONDITION.
    """

@_typing.type_check_only
class NetEventsServiceAsyncStub(NetEventsServiceStub):
    """NetEventsService carries net-gateway's record of every connection, datagram flow, and DNS
    query back to the worker that owns the run. The gateway holds the traffic until the worker
    commits the record and acks it, so a request that was let through is never unrecorded.
    Behavior: docs/services/net-gateway.md.

    Not served or called yet: net-gateway is deferred (2026-10-02). The contract is kept as
    designed so the work can resume from it.
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    Attach: _aio.StreamStreamMultiCallable[_netevents_pb2.AttachRequest, _netevents_pb2.AttachResponse]  # type: ignore[assignment]
    """One stream per run, dialed by the run's worker over mTLS with a per-run certificate. The
    worker's first message is a `Hello`; the gateway answers `Attached`. After that the gateway
    sends one `Record` per connection, datagram flow, or DNS query and holds that traffic until
    the worker answers with an `Ack` or `Reject` for it. A stream for the same run with a higher
    `owner_epoch` replaces this one; a lower or equal one is refused with FAILED_PRECONDITION.
    """

class NetEventsServiceServicer(metaclass=_abc_1.ABCMeta):
    """NetEventsService carries net-gateway's record of every connection, datagram flow, and DNS
    query back to the worker that owns the run. The gateway holds the traffic until the worker
    commits the record and acks it, so a request that was let through is never unrecorded.
    Behavior: docs/services/net-gateway.md.

    Not served or called yet: net-gateway is deferred (2026-10-02). The contract is kept as
    designed so the work can resume from it.
    """

    @_abc_1.abstractmethod
    def Attach(
        self,
        request_iterator: _MaybeAsyncIterator[_netevents_pb2.AttachRequest],
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_netevents_pb2.AttachResponse], _abc.AsyncIterator[_netevents_pb2.AttachResponse]]:
        """One stream per run, dialed by the run's worker over mTLS with a per-run certificate. The
        worker's first message is a `Hello`; the gateway answers `Attached`. After that the gateway
        sends one `Record` per connection, datagram flow, or DNS query and holds that traffic until
        the worker answers with an `Ack` or `Reject` for it. A stream for the same run with a higher
        `owner_epoch` replaces this one; a lower or equal one is refused with FAILED_PRECONDITION.
        """

def add_NetEventsServiceServicer_to_server(servicer: NetEventsServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
