"""Public API for writing and loading extensions. Import from here, not from submodules."""

from swarmeval.runtime.extensions.api import (
    API_VERSION,
    AgentInfo,
    Allow,
    Block,
    CanaryInfo,
    Extension,
    ExtensionAPI,
    ExtensionDefinitionError,
    ExtensionError,
    HookContext,
    Inject,
    NoConfig,
    NoState,
    Proceed,
    Rewrite,
    RunInfo,
    Skip,
    Stop,
    ToolDecision,
    TurnDecision,
    TurnInfo,
    extension,
)
from swarmeval.runtime.extensions.registry import (
    ENTRY_POINT_GROUP,
    ExtensionLoadError,
    ExtensionUse,
    LoadedExtension,
    load_extensions,
)
from swarmeval.runtime.messages import (
    AssistantMessage,
    ChatMessage,
    RequestOptions,
    SystemMessage,
    ToolCall,
    ToolMessage,
    UserMessage,
)
from swarmeval.runtime.records import CommittedEvent, Exec, ExecResult, ToolResult

__all__ = [
    "API_VERSION",
    "ENTRY_POINT_GROUP",
    "AgentInfo",
    "Allow",
    "AssistantMessage",
    "Block",
    "CanaryInfo",
    "ChatMessage",
    "CommittedEvent",
    "Exec",
    "ExecResult",
    "Extension",
    "ExtensionAPI",
    "ExtensionDefinitionError",
    "ExtensionError",
    "ExtensionLoadError",
    "ExtensionUse",
    "HookContext",
    "Inject",
    "LoadedExtension",
    "NoConfig",
    "NoState",
    "Proceed",
    "RequestOptions",
    "Rewrite",
    "RunInfo",
    "Skip",
    "Stop",
    "SystemMessage",
    "ToolCall",
    "ToolDecision",
    "ToolMessage",
    "ToolResult",
    "TurnDecision",
    "TurnInfo",
    "UserMessage",
    "extension",
    "load_extensions",
]
