# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from swarmeval.proto.swarmeval.analysis.v1 import analysis_pb2 as swarmeval_dot_proto_dot_swarmeval_dot_analysis_dot_v1_dot_analysis__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in swarmeval/proto/swarmeval/analysis/v1/analysis_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AnalysisServiceStub:
    """AnalysisService answers questions about exported runs: the batch jobs of
    `python -m swarmeval.analysis`, as calls. Only edge reaches it. Behavior:
    docs/services/analysis.md.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Query = channel.unary_stream(
                '/swarmeval.analysis.v1.AnalysisService/Query',
                request_serializer=swarmeval_dot_proto_dot_swarmeval_dot_analysis_dot_v1_dot_analysis__pb2.QueryRequest.SerializeToString,
                response_deserializer=swarmeval_dot_proto_dot_swarmeval_dot_analysis_dot_v1_dot_analysis__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.SearchToolCalls = channel.unary_unary(
                '/swarmeval.analysis.v1.AnalysisService/SearchToolCalls',
                request_serializer=swarmeval_dot_proto_dot_swarmeval_dot_analysis_dot_v1_dot_analysis__pb2.SearchToolCallsRequest.SerializeToString,
                response_deserializer=swarmeval_dot_proto_dot_swarmeval_dot_analysis_dot_v1_dot_analysis__pb2.SearchToolCallsResponse.FromString,
                _registered_method=True)
        self.StartRuleScan = channel.unary_unary(
                '/swarmeval.analysis.v1.AnalysisService/StartRuleScan',
                request_serializer=swarmeval_dot_proto_dot_swarmeval_dot_analysis_dot_v1_dot_analysis__pb2.StartRuleScanRequest.SerializeToString,
                response_deserializer=swarmeval_dot_proto_dot_swarmeval_dot_analysis_dot_v1_dot_analysis__pb2.StartRuleScanResponse.FromString,
                _registered_method=True)
        self.GetJob = channel.unary_unary(
                '/swarmeval.analysis.v1.AnalysisService/GetJob',
                request_serializer=swarmeval_dot_proto_dot_swarmeval_dot_analysis_dot_v1_dot_analysis__pb2.GetJobRequest.SerializeToString,
                response_deserializer=swarmeval_dot_proto_dot_swarmeval_dot_analysis_dot_v1_dot_analysis__pb2.GetJobResponse.FromString,
                _registered_method=True)
        self.Judge = channel.unary_unary(
                '/swarmeval.analysis.v1.AnalysisService/Judge',
                request_serializer=swarmeval_dot_proto_dot_swarmeval_dot_analysis_dot_v1_dot_analysis__pb2.JudgeRequest.SerializeToString,
                response_deserializer=swarmeval_dot_proto_dot_swarmeval_dot_analysis_dot_v1_dot_analysis__pb2.JudgeResponse.FromString,
                _registered_method=True)
        self.Report = channel.unary_unary(
                '/swarmeval.analysis.v1.AnalysisService/Report',
                request_serializer=swarmeval_dot_proto_dot_swarmeval_dot_analysis_dot_v1_dot_analysis__pb2.ReportRequest.SerializeToString,
                response_deserializer=swarmeval_dot_proto_dot_swarmeval_dot_analysis_dot_v1_dot_analysis__pb2.ReportResponse.FromString,
                _registered_method=True)
        self.GetTrace = channel.unary_unary(
                '/swarmeval.analysis.v1.AnalysisService/GetTrace',
                request_serializer=swarmeval_dot_proto_dot_swarmeval_dot_analysis_dot_v1_dot_analysis__pb2.GetTraceRequest.SerializeToString,
                response_deserializer=swarmeval_dot_proto_dot_swarmeval_dot_analysis_dot_v1_dot_analysis__pb2.GetTraceResponse.FromString,
                _registered_method=True)
        self.DownloadExport = channel.unary_stream(
                '/swarmeval.analysis.v1.AnalysisService/DownloadExport',
                request_serializer=swarmeval_dot_proto_dot_swarmeval_dot_analysis_dot_v1_dot_analysis__pb2.DownloadExportRequest.SerializeToString,
                response_deserializer=swarmeval_dot_proto_dot_swarmeval_dot_analysis_dot_v1_dot_analysis__pb2.DownloadExportResponse.FromString,
                _registered_method=True)


class AnalysisServiceServicer:
    """AnalysisService answers questions about exported runs: the batch jobs of
    `python -m swarmeval.analysis`, as calls. Only edge reaches it. Behavior:
    docs/services/analysis.md.
    """

    def Query(self, request, context):
        """One read-only SQL statement over the views `runs` (one row per run summary) and `events`
        (every exported run's events). The statement can read nothing else and change no setting.
        Rows come in chunks; the last message says whether the row limit cut the result. SQL that
        does not parse or run, or is not a single SELECT, is INVALID_ARGUMENT; a statement over the
        time limit is DEADLINE_EXCEEDED.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchToolCalls(self, request, context):
        """Tool calls of exported runs, by run, then seq.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartRuleScan(self, request, context):
        """Starts a rule set over runs as a background job and returns it, queued. A rule set that
        does not validate is INVALID_ARGUMENT; a selection with no exported run is NOT_FOUND.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJob(self, request, context):
        """An unknown job is NOT_FOUND.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Judge(self, request, context):
        """Asks an LLM judge one question about one run and returns its verdict, accepted or
        rejected; either way the call is stored. A run with no export is NOT_FOUND; a transcript
        that is empty or too long, or a model gateway that refuses, is FAILED_PRECONDITION.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Report(self, request, context):
        """Trigger rates per case revision, variant, and scorer over the runs of the given
        submissions and suites; all runs when both are empty.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTrace(self, request, context):
        """One event's chain of causes, the run's first event first. A run with no export or an
        event not in it is NOT_FOUND; a broken chain is FAILED_PRECONDITION.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadExport(self, request, context):
        """One of a run's exported files, in chunks. A run with no export is NOT_FOUND.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalysisServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Query': grpc.unary_stream_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=swarmeval_dot_proto_dot_swarmeval_dot_analysis_dot_v1_dot_analysis__pb2.QueryRequest.FromString,
                    response_serializer=swarmeval_dot_proto_dot_swarmeval_dot_analysis_dot_v1_dot_analysis__pb2.QueryResponse.SerializeToString,
            ),
            'SearchToolCalls': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchToolCalls,
                    request_deserializer=swarmeval_dot_proto_dot_swarmeval_dot_analysis_dot_v1_dot_analysis__pb2.SearchToolCallsRequest.FromString,
                    response_serializer=swarmeval_dot_proto_dot_swarmeval_dot_analysis_dot_v1_dot_analysis__pb2.SearchToolCallsResponse.SerializeToString,
            ),
            'StartRuleScan': grpc.unary_unary_rpc_method_handler(
                    servicer.StartRuleScan,
                    request_deserializer=swarmeval_dot_proto_dot_swarmeval_dot_analysis_dot_v1_dot_analysis__pb2.StartRuleScanRequest.FromString,
                    response_serializer=swarmeval_dot_proto_dot_swarmeval_dot_analysis_dot_v1_dot_analysis__pb2.StartRuleScanResponse.SerializeToString,
            ),
            'GetJob': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJob,
                    request_deserializer=swarmeval_dot_proto_dot_swarmeval_dot_analysis_dot_v1_dot_analysis__pb2.GetJobRequest.FromString,
                    response_serializer=swarmeval_dot_proto_dot_swarmeval_dot_analysis_dot_v1_dot_analysis__pb2.GetJobResponse.SerializeToString,
            ),
            'Judge': grpc.unary_unary_rpc_method_handler(
                    servicer.Judge,
                    request_deserializer=swarmeval_dot_proto_dot_swarmeval_dot_analysis_dot_v1_dot_analysis__pb2.JudgeRequest.FromString,
                    response_serializer=swarmeval_dot_proto_dot_swarmeval_dot_analysis_dot_v1_dot_analysis__pb2.JudgeResponse.SerializeToString,
            ),
            'Report': grpc.unary_unary_rpc_method_handler(
                    servicer.Report,
                    request_deserializer=swarmeval_dot_proto_dot_swarmeval_dot_analysis_dot_v1_dot_analysis__pb2.ReportRequest.FromString,
                    response_serializer=swarmeval_dot_proto_dot_swarmeval_dot_analysis_dot_v1_dot_analysis__pb2.ReportResponse.SerializeToString,
            ),
            'GetTrace': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrace,
                    request_deserializer=swarmeval_dot_proto_dot_swarmeval_dot_analysis_dot_v1_dot_analysis__pb2.GetTraceRequest.FromString,
                    response_serializer=swarmeval_dot_proto_dot_swarmeval_dot_analysis_dot_v1_dot_analysis__pb2.GetTraceResponse.SerializeToString,
            ),
            'DownloadExport': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadExport,
                    request_deserializer=swarmeval_dot_proto_dot_swarmeval_dot_analysis_dot_v1_dot_analysis__pb2.DownloadExportRequest.FromString,
                    response_serializer=swarmeval_dot_proto_dot_swarmeval_dot_analysis_dot_v1_dot_analysis__pb2.DownloadExportResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swarmeval.analysis.v1.AnalysisService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('swarmeval.analysis.v1.AnalysisService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnalysisService:
    """AnalysisService answers questions about exported runs: the batch jobs of
    `python -m swarmeval.analysis`, as calls. Only edge reaches it. Behavior:
    docs/services/analysis.md.
    """

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/swarmeval.analysis.v1.AnalysisService/Query',
            swarmeval_dot_proto_dot_swarmeval_dot_analysis_dot_v1_dot_analysis__pb2.QueryRequest.SerializeToString,
            swarmeval_dot_proto_dot_swarmeval_dot_analysis_dot_v1_dot_analysis__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchToolCalls(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swarmeval.analysis.v1.AnalysisService/SearchToolCalls',
            swarmeval_dot_proto_dot_swarmeval_dot_analysis_dot_v1_dot_analysis__pb2.SearchToolCallsRequest.SerializeToString,
            swarmeval_dot_proto_dot_swarmeval_dot_analysis_dot_v1_dot_analysis__pb2.SearchToolCallsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartRuleScan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swarmeval.analysis.v1.AnalysisService/StartRuleScan',
            swarmeval_dot_proto_dot_swarmeval_dot_analysis_dot_v1_dot_analysis__pb2.StartRuleScanRequest.SerializeToString,
            swarmeval_dot_proto_dot_swarmeval_dot_analysis_dot_v1_dot_analysis__pb2.StartRuleScanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swarmeval.analysis.v1.AnalysisService/GetJob',
            swarmeval_dot_proto_dot_swarmeval_dot_analysis_dot_v1_dot_analysis__pb2.GetJobRequest.SerializeToString,
            swarmeval_dot_proto_dot_swarmeval_dot_analysis_dot_v1_dot_analysis__pb2.GetJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Judge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swarmeval.analysis.v1.AnalysisService/Judge',
            swarmeval_dot_proto_dot_swarmeval_dot_analysis_dot_v1_dot_analysis__pb2.JudgeRequest.SerializeToString,
            swarmeval_dot_proto_dot_swarmeval_dot_analysis_dot_v1_dot_analysis__pb2.JudgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Report(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swarmeval.analysis.v1.AnalysisService/Report',
            swarmeval_dot_proto_dot_swarmeval_dot_analysis_dot_v1_dot_analysis__pb2.ReportRequest.SerializeToString,
            swarmeval_dot_proto_dot_swarmeval_dot_analysis_dot_v1_dot_analysis__pb2.ReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTrace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swarmeval.analysis.v1.AnalysisService/GetTrace',
            swarmeval_dot_proto_dot_swarmeval_dot_analysis_dot_v1_dot_analysis__pb2.GetTraceRequest.SerializeToString,
            swarmeval_dot_proto_dot_swarmeval_dot_analysis_dot_v1_dot_analysis__pb2.GetTraceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadExport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/swarmeval.analysis.v1.AnalysisService/DownloadExport',
            swarmeval_dot_proto_dot_swarmeval_dot_analysis_dot_v1_dot_analysis__pb2.DownloadExportRequest.SerializeToString,
            swarmeval_dot_proto_dot_swarmeval_dot_analysis_dot_v1_dot_analysis__pb2.DownloadExportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
