"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import struct_pb2 as _struct_pb2
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _ExportFormat:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ExportFormatEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ExportFormat.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    EXPORT_FORMAT_UNSPECIFIED: _ExportFormat.ValueType  # 0
    EXPORT_FORMAT_EVAL: _ExportFormat.ValueType  # 1
    """The run's Inspect log, `sample.eval`."""
    EXPORT_FORMAT_PARQUET: _ExportFormat.ValueType  # 2
    """The run's events, `events.parquet`."""

class ExportFormat(_ExportFormat, metaclass=_ExportFormatEnumTypeWrapper): ...

EXPORT_FORMAT_UNSPECIFIED: ExportFormat.ValueType  # 0
EXPORT_FORMAT_EVAL: ExportFormat.ValueType  # 1
"""The run's Inspect log, `sample.eval`."""
EXPORT_FORMAT_PARQUET: ExportFormat.ValueType  # 2
"""The run's events, `events.parquet`."""
Global___ExportFormat: _TypeAlias = ExportFormat  # noqa: Y015

@_typing.final
class QueryRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SQL_FIELD_NUMBER: _builtins.int
    MAX_ROWS_FIELD_NUMBER: _builtins.int
    sql: _builtins.str
    max_rows: _builtins.int
    """Rows to return at most. Zero means 10,000, which is also the most."""
    def __init__(
        self,
        *,
        sql: _builtins.str = ...,
        max_rows: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["max_rows", b"max_rows", "sql", b"sql"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___QueryRequest: _TypeAlias = QueryRequest  # noqa: Y015

@_typing.final
class QueryColumn(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    type: _builtins.str
    """The DuckDB type, such as `VARCHAR` or `TIMESTAMP WITH TIME ZONE`."""
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        type: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["name", b"name", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___QueryColumn: _TypeAlias = QueryColumn  # noqa: Y015

@_typing.final
class QueryResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    COLUMNS_FIELD_NUMBER: _builtins.int
    ROWS_FIELD_NUMBER: _builtins.int
    TRUNCATED_FIELD_NUMBER: _builtins.int
    truncated: _builtins.bool
    """In the last message only: the statement had more rows than `max_rows`."""
    @_builtins.property
    def columns(self) -> _containers.RepeatedCompositeFieldContainer[Global___QueryColumn]:
        """In the first message only."""

    @_builtins.property
    def rows(self) -> _containers.RepeatedCompositeFieldContainer[_struct_pb2.ListValue]:
        """One list per row, a value per column. Integers beyond 2^53, decimals, times, and binary
        values are strings.
        """

    def __init__(
        self,
        *,
        columns: _abc.Iterable[Global___QueryColumn] | None = ...,
        rows: _abc.Iterable[_struct_pb2.ListValue] | None = ...,
        truncated: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["columns", b"columns", "rows", b"rows", "truncated", b"truncated"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___QueryResponse: _TypeAlias = QueryResponse  # noqa: Y015

@_typing.final
class SearchToolCallsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_IDS_FIELD_NUMBER: _builtins.int
    SUBMISSION_IDS_FIELD_NUMBER: _builtins.int
    TOOL_FIELD_NUMBER: _builtins.int
    AGENT_ID_FIELD_NUMBER: _builtins.int
    FROM_TIME_FIELD_NUMBER: _builtins.int
    TO_TIME_FIELD_NUMBER: _builtins.int
    LIMIT_FIELD_NUMBER: _builtins.int
    tool: _builtins.str
    """The tool's name, exactly."""
    agent_id: _builtins.str
    limit: _builtins.int
    """Zero means 200; at most 2,000."""
    @_builtins.property
    def run_ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Each filter narrows; empty matches everything."""

    @_builtins.property
    def submission_ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def from_time(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def to_time(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        run_ids: _abc.Iterable[_builtins.str] | None = ...,
        submission_ids: _abc.Iterable[_builtins.str] | None = ...,
        tool: _builtins.str = ...,
        agent_id: _builtins.str = ...,
        from_time: _timestamp_pb2.Timestamp | None = ...,
        to_time: _timestamp_pb2.Timestamp | None = ...,
        limit: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["from_time", b"from_time", "to_time", b"to_time"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["agent_id", b"agent_id", "from_time", b"from_time", "limit", b"limit", "run_ids", b"run_ids", "submission_ids", b"submission_ids", "to_time", b"to_time", "tool", b"tool"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SearchToolCallsRequest: _TypeAlias = SearchToolCallsRequest  # noqa: Y015

@_typing.final
class ToolCall(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    SEQ_FIELD_NUMBER: _builtins.int
    EVENT_ID_FIELD_NUMBER: _builtins.int
    TIME_FIELD_NUMBER: _builtins.int
    AGENT_ID_FIELD_NUMBER: _builtins.int
    TOOL_FIELD_NUMBER: _builtins.int
    ARGUMENTS_JSON_FIELD_NUMBER: _builtins.int
    RESULT_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    seq: _builtins.int
    event_id: _builtins.str
    agent_id: _builtins.str
    tool: _builtins.str
    arguments_json: _builtins.str
    """The call's arguments, as JSON."""
    result: _builtins.str
    """The start of the result as text, at most 2,000 characters."""
    error: _builtins.str
    """The tool's error, when the call failed."""
    @_builtins.property
    def time(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
        seq: _builtins.int = ...,
        event_id: _builtins.str = ...,
        time: _timestamp_pb2.Timestamp | None = ...,
        agent_id: _builtins.str = ...,
        tool: _builtins.str = ...,
        arguments_json: _builtins.str = ...,
        result: _builtins.str = ...,
        error: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["time", b"time"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["agent_id", b"agent_id", "arguments_json", b"arguments_json", "error", b"error", "event_id", b"event_id", "result", b"result", "run_id", b"run_id", "seq", b"seq", "time", b"time", "tool", b"tool"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ToolCall: _TypeAlias = ToolCall  # noqa: Y015

@_typing.final
class SearchToolCallsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CALLS_FIELD_NUMBER: _builtins.int
    TRUNCATED_FIELD_NUMBER: _builtins.int
    truncated: _builtins.bool
    """More calls matched than `limit`."""
    @_builtins.property
    def calls(self) -> _containers.RepeatedCompositeFieldContainer[Global___ToolCall]: ...
    def __init__(
        self,
        *,
        calls: _abc.Iterable[Global___ToolCall] | None = ...,
        truncated: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["calls", b"calls", "truncated", b"truncated"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SearchToolCallsResponse: _TypeAlias = SearchToolCallsResponse  # noqa: Y015

@_typing.final
class StartRuleScanRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RULES_YAML_FIELD_NUMBER: _builtins.int
    RUN_IDS_FIELD_NUMBER: _builtins.int
    SUBMISSION_IDS_FIELD_NUMBER: _builtins.int
    ACTOR_FIELD_NUMBER: _builtins.int
    rules_yaml: _builtins.str
    """The rule set file as written (docs/services/analysis.md#rule-sets)."""
    actor: _builtins.str
    """Who asks, as edge authenticated them. Recorded on the job."""
    @_builtins.property
    def run_ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """The runs to scan: these runs, and every exported run of these submissions."""

    @_builtins.property
    def submission_ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        rules_yaml: _builtins.str = ...,
        run_ids: _abc.Iterable[_builtins.str] | None = ...,
        submission_ids: _abc.Iterable[_builtins.str] | None = ...,
        actor: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["actor", b"actor", "rules_yaml", b"rules_yaml", "run_ids", b"run_ids", "submission_ids", b"submission_ids"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StartRuleScanRequest: _TypeAlias = StartRuleScanRequest  # noqa: Y015

@_typing.final
class StartRuleScanResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    JOB_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def job(self) -> Global___Job: ...
    def __init__(
        self,
        *,
        job: Global___Job | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["job", b"job"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["job", b"job"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StartRuleScanResponse: _TypeAlias = StartRuleScanResponse  # noqa: Y015

@_typing.final
class Job(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    JOB_ID_FIELD_NUMBER: _builtins.int
    KIND_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    ACTOR_FIELD_NUMBER: _builtins.int
    CREATED_AT_FIELD_NUMBER: _builtins.int
    FINISHED_AT_FIELD_NUMBER: _builtins.int
    RULE_SCAN_FIELD_NUMBER: _builtins.int
    job_id: _builtins.str
    kind: _builtins.str
    """`rule_scan`."""
    status: _builtins.str
    """`queued`, `running`, `done`, or `failed`."""
    error: _builtins.str
    """Why the job failed."""
    actor: _builtins.str
    @_builtins.property
    def created_at(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def finished_at(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def rule_scan(self) -> Global___RuleScanResult:
        """Set once a rule scan is `done`."""

    def __init__(
        self,
        *,
        job_id: _builtins.str = ...,
        kind: _builtins.str = ...,
        status: _builtins.str = ...,
        error: _builtins.str = ...,
        actor: _builtins.str = ...,
        created_at: _timestamp_pb2.Timestamp | None = ...,
        finished_at: _timestamp_pb2.Timestamp | None = ...,
        rule_scan: Global___RuleScanResult | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["created_at", b"created_at", "finished_at", b"finished_at", "rule_scan", b"rule_scan"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["actor", b"actor", "created_at", b"created_at", "error", b"error", "finished_at", b"finished_at", "job_id", b"job_id", "kind", b"kind", "rule_scan", b"rule_scan", "status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Job: _TypeAlias = Job  # noqa: Y015

@_typing.final
class RuleScanResult(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RULE_SET_SHA256_FIELD_NUMBER: _builtins.int
    RUNS_FIELD_NUMBER: _builtins.int
    MATCHES_FIELD_NUMBER: _builtins.int
    TOTAL_MATCHES_FIELD_NUMBER: _builtins.int
    rule_set_sha256: _builtins.str
    """sha256 of the rule set; `analysis.rule_matches` holds the matches under it."""
    total_matches: _builtins.int
    @_builtins.property
    def runs(self) -> _containers.RepeatedCompositeFieldContainer[Global___RuleScanRun]:
        """One per run scanned."""

    @_builtins.property
    def matches(self) -> _containers.RepeatedCompositeFieldContainer[Global___RuleMatch]:
        """The first matches, by run, then seq: at most 500."""

    def __init__(
        self,
        *,
        rule_set_sha256: _builtins.str = ...,
        runs: _abc.Iterable[Global___RuleScanRun] | None = ...,
        matches: _abc.Iterable[Global___RuleMatch] | None = ...,
        total_matches: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["matches", b"matches", "rule_set_sha256", b"rule_set_sha256", "runs", b"runs", "total_matches", b"total_matches"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RuleScanResult: _TypeAlias = RuleScanResult  # noqa: Y015

@_typing.final
class RuleScanRun(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    MATCHES_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    matches: _builtins.int
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
        matches: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["matches", b"matches", "run_id", b"run_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RuleScanRun: _TypeAlias = RuleScanRun  # noqa: Y015

@_typing.final
class RuleMatch(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    SEQ_FIELD_NUMBER: _builtins.int
    EVENT_ID_FIELD_NUMBER: _builtins.int
    RULE_ID_FIELD_NUMBER: _builtins.int
    FIELD_FIELD_NUMBER: _builtins.int
    VIA_FIELD_NUMBER: _builtins.int
    EXCERPT_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    seq: _builtins.int
    event_id: _builtins.str
    rule_id: _builtins.str
    field: _builtins.str
    """The payload path the match was in."""
    excerpt: _builtins.str
    @_builtins.property
    def via(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """The decodings the match was found through, outermost first."""

    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
        seq: _builtins.int = ...,
        event_id: _builtins.str = ...,
        rule_id: _builtins.str = ...,
        field: _builtins.str = ...,
        via: _abc.Iterable[_builtins.str] | None = ...,
        excerpt: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["event_id", b"event_id", "excerpt", b"excerpt", "field", b"field", "rule_id", b"rule_id", "run_id", b"run_id", "seq", b"seq", "via", b"via"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RuleMatch: _TypeAlias = RuleMatch  # noqa: Y015

@_typing.final
class GetJobRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    JOB_ID_FIELD_NUMBER: _builtins.int
    job_id: _builtins.str
    def __init__(
        self,
        *,
        job_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["job_id", b"job_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetJobRequest: _TypeAlias = GetJobRequest  # noqa: Y015

@_typing.final
class GetJobResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    JOB_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def job(self) -> Global___Job: ...
    def __init__(
        self,
        *,
        job: Global___Job | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["job", b"job"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["job", b"job"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetJobResponse: _TypeAlias = GetJobResponse  # noqa: Y015

@_typing.final
class JudgeRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    QUESTION_FIELD_NUMBER: _builtins.int
    MODEL_FIELD_NUMBER: _builtins.int
    FROM_SEQ_FIELD_NUMBER: _builtins.int
    TO_SEQ_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    question: _builtins.str
    model: _builtins.str
    """A model name the model gateway serves."""
    from_seq: _builtins.int
    """The events to show the judge; zero for no bound."""
    to_seq: _builtins.int
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
        question: _builtins.str = ...,
        model: _builtins.str = ...,
        from_seq: _builtins.int = ...,
        to_seq: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["from_seq", b"from_seq", "model", b"model", "question", b"question", "run_id", b"run_id", "to_seq", b"to_seq"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___JudgeRequest: _TypeAlias = JudgeRequest  # noqa: Y015

@_typing.final
class JudgeResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STATUS_FIELD_NUMBER: _builtins.int
    ANSWER_FIELD_NUMBER: _builtins.int
    EXPLANATION_FIELD_NUMBER: _builtins.int
    CITATIONS_FIELD_NUMBER: _builtins.int
    REJECTION_FIELD_NUMBER: _builtins.int
    status: _builtins.str
    """`accepted` or `rejected`."""
    answer: _builtins.str
    """`yes`, `no`, or `unclear`; empty for a rejected verdict."""
    explanation: _builtins.str
    rejection: _builtins.str
    """Why the verdict was rejected."""
    @_builtins.property
    def citations(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Ids of the events the verdict rests on."""

    def __init__(
        self,
        *,
        status: _builtins.str = ...,
        answer: _builtins.str = ...,
        explanation: _builtins.str = ...,
        citations: _abc.Iterable[_builtins.str] | None = ...,
        rejection: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["answer", b"answer", "citations", b"citations", "explanation", b"explanation", "rejection", b"rejection", "status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___JudgeResponse: _TypeAlias = JudgeResponse  # noqa: Y015

@_typing.final
class ReportRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUBMISSION_IDS_FIELD_NUMBER: _builtins.int
    SUITES_FIELD_NUMBER: _builtins.int
    COMPARE_FIELD_NUMBER: _builtins.int
    compare: _builtins.str
    """`AXIS=A,B`: also the difference in rate between two values of one variant axis. Empty for
    none.
    """
    @_builtins.property
    def submission_ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def suites(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        submission_ids: _abc.Iterable[_builtins.str] | None = ...,
        suites: _abc.Iterable[_builtins.str] | None = ...,
        compare: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["compare", b"compare", "submission_ids", b"submission_ids", "suites", b"suites"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReportRequest: _TypeAlias = ReportRequest  # noqa: Y015

@_typing.final
class Rate(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CASE_ID_FIELD_NUMBER: _builtins.int
    CASE_SHA256_FIELD_NUMBER: _builtins.int
    VARIANT_FIELD_NUMBER: _builtins.int
    VARIANT_VALUES_JSON_FIELD_NUMBER: _builtins.int
    SCORER_FIELD_NUMBER: _builtins.int
    EPOCHS_FIELD_NUMBER: _builtins.int
    RATE_FIELD_NUMBER: _builtins.int
    STDERR_FIELD_NUMBER: _builtins.int
    CI_LOW_FIELD_NUMBER: _builtins.int
    CI_HIGH_FIELD_NUMBER: _builtins.int
    case_id: _builtins.str
    case_sha256: _builtins.str
    variant: _builtins.int
    variant_values_json: _builtins.str
    """The variant's axis values, as JSON with sorted keys."""
    scorer: _builtins.str
    epochs: _builtins.int
    """`done` runs this scorer scored."""
    rate: _builtins.float
    stderr: _builtins.float
    """Of the mean; unset with one epoch."""
    ci_low: _builtins.float
    """The 95% Wilson interval."""
    ci_high: _builtins.float
    def __init__(
        self,
        *,
        case_id: _builtins.str = ...,
        case_sha256: _builtins.str = ...,
        variant: _builtins.int = ...,
        variant_values_json: _builtins.str = ...,
        scorer: _builtins.str = ...,
        epochs: _builtins.int = ...,
        rate: _builtins.float = ...,
        stderr: _builtins.float | None = ...,
        ci_low: _builtins.float = ...,
        ci_high: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_stderr", b"_stderr", "stderr", b"stderr"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_stderr", b"_stderr", "case_id", b"case_id", "case_sha256", b"case_sha256", "ci_high", b"ci_high", "ci_low", b"ci_low", "epochs", b"epochs", "rate", b"rate", "scorer", b"scorer", "stderr", b"stderr", "variant", b"variant", "variant_values_json", b"variant_values_json"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__stderr: _TypeAlias = _typing.Literal["stderr"]  # noqa: Y015
    _WhichOneofArgType__stderr: _TypeAlias = _typing.Literal["_stderr", b"_stderr"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__stderr) -> _WhichOneofReturnType__stderr | None: ...

Global___Rate: _TypeAlias = Rate  # noqa: Y015

@_typing.final
class Unscored(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CASE_ID_FIELD_NUMBER: _builtins.int
    CASE_SHA256_FIELD_NUMBER: _builtins.int
    VARIANT_FIELD_NUMBER: _builtins.int
    VARIANT_VALUES_JSON_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    RUNS_FIELD_NUMBER: _builtins.int
    case_id: _builtins.str
    case_sha256: _builtins.str
    variant: _builtins.int
    variant_values_json: _builtins.str
    status: _builtins.str
    runs: _builtins.int
    def __init__(
        self,
        *,
        case_id: _builtins.str = ...,
        case_sha256: _builtins.str = ...,
        variant: _builtins.int = ...,
        variant_values_json: _builtins.str = ...,
        status: _builtins.str = ...,
        runs: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["case_id", b"case_id", "case_sha256", b"case_sha256", "runs", b"runs", "status", b"status", "variant", b"variant", "variant_values_json", b"variant_values_json"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Unscored: _TypeAlias = Unscored  # noqa: Y015

@_typing.final
class Coverage(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CASE_ID_FIELD_NUMBER: _builtins.int
    CASE_SHA256_FIELD_NUMBER: _builtins.int
    VARIANT_FIELD_NUMBER: _builtins.int
    VARIANT_VALUES_JSON_FIELD_NUMBER: _builtins.int
    REQUESTED_FIELD_NUMBER: _builtins.int
    DONE_FIELD_NUMBER: _builtins.int
    REPLACED_FIELD_NUMBER: _builtins.int
    MISSING_FIELD_NUMBER: _builtins.int
    case_id: _builtins.str
    case_sha256: _builtins.str
    variant: _builtins.int
    variant_values_json: _builtins.str
    requested: _builtins.int
    done: _builtins.int
    replaced: _builtins.int
    """Interrupted runs that were rerun at a new epoch."""
    missing: _builtins.int
    def __init__(
        self,
        *,
        case_id: _builtins.str = ...,
        case_sha256: _builtins.str = ...,
        variant: _builtins.int = ...,
        variant_values_json: _builtins.str = ...,
        requested: _builtins.int = ...,
        done: _builtins.int = ...,
        replaced: _builtins.int = ...,
        missing: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["case_id", b"case_id", "case_sha256", b"case_sha256", "done", b"done", "missing", b"missing", "replaced", b"replaced", "requested", b"requested", "variant", b"variant", "variant_values_json", b"variant_values_json"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Coverage: _TypeAlias = Coverage  # noqa: Y015

@_typing.final
class ForkScore(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    FORKED_FROM_FIELD_NUMBER: _builtins.int
    FORK_SEQ_FIELD_NUMBER: _builtins.int
    FIDELITY_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    SCORER_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    forked_from: _builtins.str
    fork_seq: _builtins.int
    fidelity: _builtins.str
    status: _builtins.str
    scorer: _builtins.str
    """Empty, with `value` unset, for a fork no scorer scored."""
    value: _builtins.float
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
        forked_from: _builtins.str = ...,
        fork_seq: _builtins.int = ...,
        fidelity: _builtins.str = ...,
        status: _builtins.str = ...,
        scorer: _builtins.str = ...,
        value: _builtins.float | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_value", b"_value", "value", b"value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_value", b"_value", "fidelity", b"fidelity", "fork_seq", b"fork_seq", "forked_from", b"forked_from", "run_id", b"run_id", "scorer", b"scorer", "status", b"status", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__value: _TypeAlias = _typing.Literal["value"]  # noqa: Y015
    _WhichOneofArgType__value: _TypeAlias = _typing.Literal["_value", b"_value"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__value) -> _WhichOneofReturnType__value | None: ...

Global___ForkScore: _TypeAlias = ForkScore  # noqa: Y015

@_typing.final
class Difference(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CASE_ID_FIELD_NUMBER: _builtins.int
    CASE_SHA256_FIELD_NUMBER: _builtins.int
    SCORER_FIELD_NUMBER: _builtins.int
    OTHERS_JSON_FIELD_NUMBER: _builtins.int
    A_FIELD_NUMBER: _builtins.int
    B_FIELD_NUMBER: _builtins.int
    DIFF_FIELD_NUMBER: _builtins.int
    CI_LOW_FIELD_NUMBER: _builtins.int
    CI_HIGH_FIELD_NUMBER: _builtins.int
    case_id: _builtins.str
    case_sha256: _builtins.str
    scorer: _builtins.str
    others_json: _builtins.str
    """The other axes' values, as JSON with sorted keys."""
    diff: _builtins.float
    """`b.rate - a.rate`, with its 95% interval by Newcombe's method."""
    ci_low: _builtins.float
    ci_high: _builtins.float
    @_builtins.property
    def a(self) -> Global___Rate: ...
    @_builtins.property
    def b(self) -> Global___Rate: ...
    def __init__(
        self,
        *,
        case_id: _builtins.str = ...,
        case_sha256: _builtins.str = ...,
        scorer: _builtins.str = ...,
        others_json: _builtins.str = ...,
        a: Global___Rate | None = ...,
        b: Global___Rate | None = ...,
        diff: _builtins.float = ...,
        ci_low: _builtins.float = ...,
        ci_high: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["a", b"a", "b", b"b"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["a", b"a", "b", b"b", "case_id", b"case_id", "case_sha256", b"case_sha256", "ci_high", b"ci_high", "ci_low", b"ci_low", "diff", b"diff", "others_json", b"others_json", "scorer", b"scorer"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Difference: _TypeAlias = Difference  # noqa: Y015

@_typing.final
class ReportResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RATES_FIELD_NUMBER: _builtins.int
    UNSCORED_FIELD_NUMBER: _builtins.int
    COVERAGE_FIELD_NUMBER: _builtins.int
    FORKS_FIELD_NUMBER: _builtins.int
    DIFFERENCES_FIELD_NUMBER: _builtins.int
    MARKDOWN_FIELD_NUMBER: _builtins.int
    markdown: _builtins.str
    """The whole report as Markdown, as `python -m swarmeval.analysis report` prints it."""
    @_builtins.property
    def rates(self) -> _containers.RepeatedCompositeFieldContainer[Global___Rate]: ...
    @_builtins.property
    def unscored(self) -> _containers.RepeatedCompositeFieldContainer[Global___Unscored]:
        """Runs left out of the rates because they did not end `done`."""

    @_builtins.property
    def coverage(self) -> _containers.RepeatedCompositeFieldContainer[Global___Coverage]: ...
    @_builtins.property
    def forks(self) -> _containers.RepeatedCompositeFieldContainer[Global___ForkScore]: ...
    @_builtins.property
    def differences(self) -> _containers.RepeatedCompositeFieldContainer[Global___Difference]:
        """With `compare`."""

    def __init__(
        self,
        *,
        rates: _abc.Iterable[Global___Rate] | None = ...,
        unscored: _abc.Iterable[Global___Unscored] | None = ...,
        coverage: _abc.Iterable[Global___Coverage] | None = ...,
        forks: _abc.Iterable[Global___ForkScore] | None = ...,
        differences: _abc.Iterable[Global___Difference] | None = ...,
        markdown: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["coverage", b"coverage", "differences", b"differences", "forks", b"forks", "markdown", b"markdown", "rates", b"rates", "unscored", b"unscored"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReportResponse: _TypeAlias = ReportResponse  # noqa: Y015

@_typing.final
class GetTraceRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    EVENT_ID_FIELD_NUMBER: _builtins.int
    EVENT_CHARS_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    event_id: _builtins.str
    event_chars: _builtins.int
    """Characters of each event's text. Zero means 400."""
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
        event_id: _builtins.str = ...,
        event_chars: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["event_chars", b"event_chars", "event_id", b"event_id", "run_id", b"run_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetTraceRequest: _TypeAlias = GetTraceRequest  # noqa: Y015

@_typing.final
class TraceLink(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    SEQ_FIELD_NUMBER: _builtins.int
    EVENT_ID_FIELD_NUMBER: _builtins.int
    AGENT_ID_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    LINE_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    """The run the event is in: a fork's chain goes on into its source."""
    seq: _builtins.int
    event_id: _builtins.str
    agent_id: _builtins.str
    type: _builtins.str
    line: _builtins.str
    """The event on one line, as the judge reads it."""
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
        seq: _builtins.int = ...,
        event_id: _builtins.str = ...,
        agent_id: _builtins.str = ...,
        type: _builtins.str = ...,
        line: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["agent_id", b"agent_id", "event_id", b"event_id", "line", b"line", "run_id", b"run_id", "seq", b"seq", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TraceLink: _TypeAlias = TraceLink  # noqa: Y015

@_typing.final
class GetTraceResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    LINKS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def links(self) -> _containers.RepeatedCompositeFieldContainer[Global___TraceLink]:
        """The run's first event first, the traced event last."""

    def __init__(
        self,
        *,
        links: _abc.Iterable[Global___TraceLink] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["links", b"links"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetTraceResponse: _TypeAlias = GetTraceResponse  # noqa: Y015

@_typing.final
class DownloadExportRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    FORMAT_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    format: Global___ExportFormat.ValueType
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
        format: Global___ExportFormat.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["format", b"format", "run_id", b"run_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DownloadExportRequest: _TypeAlias = DownloadExportRequest  # noqa: Y015

@_typing.final
class DownloadExportResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CHUNK_FIELD_NUMBER: _builtins.int
    chunk: _builtins.bytes
    """The file's next bytes, at most 1 MiB."""
    def __init__(
        self,
        *,
        chunk: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["chunk", b"chunk"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DownloadExportResponse: _TypeAlias = DownloadExportResponse  # noqa: Y015
