"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
from swarmeval.proto.swarmeval.analysis.v1 import analysis_pb2 as _analysis_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class AnalysisServiceStub:
    """AnalysisService answers questions about exported runs: the batch jobs of
    `python -m swarmeval.analysis`, as calls. Only edge reaches it. Behavior:
    docs/services/analysis.md.
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> AnalysisServiceAsyncStub: ...
    Query: _grpc.UnaryStreamMultiCallable[_analysis_pb2.QueryRequest, _analysis_pb2.QueryResponse]
    """One read-only SQL statement over the views `runs` (one row per run summary) and `events`
    (every exported run's events). The statement can read nothing else and change no setting.
    Rows come in chunks; the last message says whether the row limit cut the result. SQL that
    does not parse or run, or is not a single SELECT, is INVALID_ARGUMENT; a statement over the
    time limit is DEADLINE_EXCEEDED.
    """
    SearchToolCalls: _grpc.UnaryUnaryMultiCallable[_analysis_pb2.SearchToolCallsRequest, _analysis_pb2.SearchToolCallsResponse]
    """Tool calls of exported runs, by run, then seq."""
    StartRuleScan: _grpc.UnaryUnaryMultiCallable[_analysis_pb2.StartRuleScanRequest, _analysis_pb2.StartRuleScanResponse]
    """Starts a rule set over runs as a background job and returns it, queued. A rule set that
    does not validate is INVALID_ARGUMENT; a selection with no exported run is NOT_FOUND.
    """
    GetJob: _grpc.UnaryUnaryMultiCallable[_analysis_pb2.GetJobRequest, _analysis_pb2.GetJobResponse]
    """An unknown job is NOT_FOUND."""
    Judge: _grpc.UnaryUnaryMultiCallable[_analysis_pb2.JudgeRequest, _analysis_pb2.JudgeResponse]
    """Asks an LLM judge one question about one run and returns its verdict, accepted or
    rejected; either way the call is stored. A run with no export is NOT_FOUND; a transcript
    that is empty or too long, or a model gateway that refuses, is FAILED_PRECONDITION.
    """
    Report: _grpc.UnaryUnaryMultiCallable[_analysis_pb2.ReportRequest, _analysis_pb2.ReportResponse]
    """Trigger rates per case revision, variant, and scorer over the runs of the given
    submissions and suites; all runs when both are empty.
    """
    GetTrace: _grpc.UnaryUnaryMultiCallable[_analysis_pb2.GetTraceRequest, _analysis_pb2.GetTraceResponse]
    """One event's chain of causes, the run's first event first. A run with no export or an
    event not in it is NOT_FOUND; a broken chain is FAILED_PRECONDITION.
    """
    DownloadExport: _grpc.UnaryStreamMultiCallable[_analysis_pb2.DownloadExportRequest, _analysis_pb2.DownloadExportResponse]
    """One of a run's exported files, in chunks. A run with no export is NOT_FOUND."""

@_typing.type_check_only
class AnalysisServiceAsyncStub(AnalysisServiceStub):
    """AnalysisService answers questions about exported runs: the batch jobs of
    `python -m swarmeval.analysis`, as calls. Only edge reaches it. Behavior:
    docs/services/analysis.md.
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    Query: _aio.UnaryStreamMultiCallable[_analysis_pb2.QueryRequest, _analysis_pb2.QueryResponse]  # type: ignore[assignment]
    """One read-only SQL statement over the views `runs` (one row per run summary) and `events`
    (every exported run's events). The statement can read nothing else and change no setting.
    Rows come in chunks; the last message says whether the row limit cut the result. SQL that
    does not parse or run, or is not a single SELECT, is INVALID_ARGUMENT; a statement over the
    time limit is DEADLINE_EXCEEDED.
    """
    SearchToolCalls: _aio.UnaryUnaryMultiCallable[_analysis_pb2.SearchToolCallsRequest, _analysis_pb2.SearchToolCallsResponse]  # type: ignore[assignment]
    """Tool calls of exported runs, by run, then seq."""
    StartRuleScan: _aio.UnaryUnaryMultiCallable[_analysis_pb2.StartRuleScanRequest, _analysis_pb2.StartRuleScanResponse]  # type: ignore[assignment]
    """Starts a rule set over runs as a background job and returns it, queued. A rule set that
    does not validate is INVALID_ARGUMENT; a selection with no exported run is NOT_FOUND.
    """
    GetJob: _aio.UnaryUnaryMultiCallable[_analysis_pb2.GetJobRequest, _analysis_pb2.GetJobResponse]  # type: ignore[assignment]
    """An unknown job is NOT_FOUND."""
    Judge: _aio.UnaryUnaryMultiCallable[_analysis_pb2.JudgeRequest, _analysis_pb2.JudgeResponse]  # type: ignore[assignment]
    """Asks an LLM judge one question about one run and returns its verdict, accepted or
    rejected; either way the call is stored. A run with no export is NOT_FOUND; a transcript
    that is empty or too long, or a model gateway that refuses, is FAILED_PRECONDITION.
    """
    Report: _aio.UnaryUnaryMultiCallable[_analysis_pb2.ReportRequest, _analysis_pb2.ReportResponse]  # type: ignore[assignment]
    """Trigger rates per case revision, variant, and scorer over the runs of the given
    submissions and suites; all runs when both are empty.
    """
    GetTrace: _aio.UnaryUnaryMultiCallable[_analysis_pb2.GetTraceRequest, _analysis_pb2.GetTraceResponse]  # type: ignore[assignment]
    """One event's chain of causes, the run's first event first. A run with no export or an
    event not in it is NOT_FOUND; a broken chain is FAILED_PRECONDITION.
    """
    DownloadExport: _aio.UnaryStreamMultiCallable[_analysis_pb2.DownloadExportRequest, _analysis_pb2.DownloadExportResponse]  # type: ignore[assignment]
    """One of a run's exported files, in chunks. A run with no export is NOT_FOUND."""

class AnalysisServiceServicer(metaclass=_abc_1.ABCMeta):
    """AnalysisService answers questions about exported runs: the batch jobs of
    `python -m swarmeval.analysis`, as calls. Only edge reaches it. Behavior:
    docs/services/analysis.md.
    """

    @_abc_1.abstractmethod
    def Query(
        self,
        request: _analysis_pb2.QueryRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_analysis_pb2.QueryResponse], _abc.AsyncIterator[_analysis_pb2.QueryResponse]]:
        """One read-only SQL statement over the views `runs` (one row per run summary) and `events`
        (every exported run's events). The statement can read nothing else and change no setting.
        Rows come in chunks; the last message says whether the row limit cut the result. SQL that
        does not parse or run, or is not a single SELECT, is INVALID_ARGUMENT; a statement over the
        time limit is DEADLINE_EXCEEDED.
        """

    @_abc_1.abstractmethod
    def SearchToolCalls(
        self,
        request: _analysis_pb2.SearchToolCallsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_analysis_pb2.SearchToolCallsResponse, _abc.Awaitable[_analysis_pb2.SearchToolCallsResponse]]:
        """Tool calls of exported runs, by run, then seq."""

    @_abc_1.abstractmethod
    def StartRuleScan(
        self,
        request: _analysis_pb2.StartRuleScanRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_analysis_pb2.StartRuleScanResponse, _abc.Awaitable[_analysis_pb2.StartRuleScanResponse]]:
        """Starts a rule set over runs as a background job and returns it, queued. A rule set that
        does not validate is INVALID_ARGUMENT; a selection with no exported run is NOT_FOUND.
        """

    @_abc_1.abstractmethod
    def GetJob(
        self,
        request: _analysis_pb2.GetJobRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_analysis_pb2.GetJobResponse, _abc.Awaitable[_analysis_pb2.GetJobResponse]]:
        """An unknown job is NOT_FOUND."""

    @_abc_1.abstractmethod
    def Judge(
        self,
        request: _analysis_pb2.JudgeRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_analysis_pb2.JudgeResponse, _abc.Awaitable[_analysis_pb2.JudgeResponse]]:
        """Asks an LLM judge one question about one run and returns its verdict, accepted or
        rejected; either way the call is stored. A run with no export is NOT_FOUND; a transcript
        that is empty or too long, or a model gateway that refuses, is FAILED_PRECONDITION.
        """

    @_abc_1.abstractmethod
    def Report(
        self,
        request: _analysis_pb2.ReportRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_analysis_pb2.ReportResponse, _abc.Awaitable[_analysis_pb2.ReportResponse]]:
        """Trigger rates per case revision, variant, and scorer over the runs of the given
        submissions and suites; all runs when both are empty.
        """

    @_abc_1.abstractmethod
    def GetTrace(
        self,
        request: _analysis_pb2.GetTraceRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_analysis_pb2.GetTraceResponse, _abc.Awaitable[_analysis_pb2.GetTraceResponse]]:
        """One event's chain of causes, the run's first event first. A run with no export or an
        event not in it is NOT_FOUND; a broken chain is FAILED_PRECONDITION.
        """

    @_abc_1.abstractmethod
    def DownloadExport(
        self,
        request: _analysis_pb2.DownloadExportRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_analysis_pb2.DownloadExportResponse], _abc.AsyncIterator[_analysis_pb2.DownloadExportResponse]]:
        """One of a run's exported files, in chunks. A run with no export is NOT_FOUND."""

def add_AnalysisServiceServicer_to_server(servicer: AnalysisServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
